### ISSUE TITLE
Better mineshafts compatibility issue

### ISSUE THREAD

**Issue by Hadies-Alchemist** [TeamTwilight/twilightforest#1039]
Forge version: 
Twilight Forest version: (this is the build number)
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)

Steps to reproduce:
1. install better mineshafts and twilight forest. Load game and then load world. enter twilight dimension and explore until you find the floating mineshafts.

What I expected to happen: there to not be floating mineshafts in the sky

What happened instead: there were floating mineshafts in the sky
![2021-04-04_20 39 06](https://user-images.githubusercontent.com/59758314/113535877-7f13e300-9589-11eb-8643-e769256f85ae.png)

**Comment by Neko2n** [comment]
I can confirm I have this issue as well. I also only saw the acacia mineshaft in the oak savanna, no other mineshafts in any other biomes.

**Comment by Tamaized** [comment]
This is their issue not ours

**Comment by TelepathicGrunt** [comment]
@Hadies-Alchemist @NovaN4  this is repurposed structures's mineshafts. Please use my configs to blacklist dimensions or biomes to prevent my structures from spawning in certain dimensions/biomes. I add my structures using a pretty broad selection to biomes and I can't account for all the possible dimension mods that can exist lol. hence why it is best for user to blacklist it in their config rather than me hardcoding checks as some people may want the mineshafts in other dimensions

I can add their dimension to the default string for the dimension blacklist but it wont affect people who already started playing with RS as the config is already made. For them, they will have to still edit config to blacklist the dimension

**Comment by zachsai** [comment]
> @Hadies-Alchemist @NovaN4 this is repurposed structures's mineshafts. Please use my configs to blacklist dimensions or biomes to prevent my structures from spawning in certain dimensions/biomes. I add my structures using a pretty broad selection to biomes and I can't account for all the possible dimension mods that can exist lol. hence why it is best for user to blacklist it in their config rather than me hardcoding checks as some people may want the mineshafts in other dimensions
> 
> I can add their dimension to the default string for the dimension blacklist but it wont affect people who already started playing with RS as the config is already made. For them, they will have to still edit config to blacklist the dimension

Can you add a blacklist dimension config so we do not have to manually add all the biomes from other dimensions?

**Comment by TelepathicGrunt** [comment]
@celsiusqc There's already a dimension blacklist. It's in the main config file and applies to all Repurposed Structures's structrues at once
