### ISSUE TITLE
UR ghast loot chest

### ISSUE THREAD

**Issue by ghost** [TeamTwilight/twilightforest#1080]
Forge version:  latest 
Twilight Forest version: latest
Link to crash log: N/A

Steps to reproduce:
1. Break the middle of the floor in the UR ghast battle area

What I expected to happen: loot chest appear after i kill UR ghast

What happened instead: The chest didn't appear, likely because the floor was broken due to... something, a fireball or creeper or so.

**Comment by Tamaized** [comment]
Please do not use `latest` when writing a report. This isn't helpful.

**Comment by BurnutsGaming** [comment]
I have to recreate this version because you used  #latest.

**Comment by GizmoTheMoonPig** [comment]
the Ur-ghast's loot chest will always be forced into a certain spot, no matter what's there. If you don't see a chest its likely something broke it after it was placed, the contents should be somewhere around the area. If you can consistently reproduce this, feel free to repoen this and send me the modlist, coords, and seed, and I will be happy to troubleshoot it for you. Otherwise I'm gonna consider this an unlucky event because I don't see any other way this could have happened
