### ISSUE TITLE
[Suggestion] Update Twilight Lakes and Twilight Streams with new Vanilla 1.13+ Blocks and mobs

### ISSUE THREAD

**Issue by The-Bernician-Lamb** [TeamTwilight/twilightforest#1088]
Having played Modern Vanilla Minecraft (1.13+) Versions in survival for a while now I've noticed that when coming back to the Twilight Forest after so many changes to vanilla it really makes the Twilight Lakes and Twilight Streams feel quite dated in comparison to the New Vanilla River and Ocean Biomes.

Vanilla River:
![2021-04-18_23 20 49](https://user-images.githubusercontent.com/64381954/115163120-3dae2800-a09f-11eb-8833-3a8206b56824.png)
Twilight Stream:
![2021-04-18_23 22 37](https://user-images.githubusercontent.com/64381954/115163134-4dc60780-a09f-11eb-8257-9336b58e7bf3.png)
Vanilla Ocean:
![2021-04-18_23 23 38](https://user-images.githubusercontent.com/64381954/115163159-60d8d780-a09f-11eb-9c91-ab57177c2405.png)
Twilight Lake:
![2021-04-18_23 26 51](https://user-images.githubusercontent.com/64381954/115163164-72ba7a80-a09f-11eb-8b6b-718a5da2e42b.png)
Just comparing the two makes me feel like the Twilight Lakes and Twilight Streams are just missing any kind of life. It's something I would have overlooked prior to 1.13 but after being on modern versions for so long it really makes the Twilight Lakes and Streams feel really lacking and outdated. 

I feel like utilizing a lot of the new 1.13 ocean features in these biomes (Or creating your own) would go a long way to making them feel much more modern and up to date! You don't have to add everything just whatever you feel would fit with the Twilight Forest and add more life to these biomes. I imagine you probably already had some plans for these biomes but I still thought it was worth mentioning as something to think about for the future.

Thanks!

**Comment by GizmoTheMoonPig** [comment]
forgot this was still open. 
I added seagrass, sand, and clay to streams and lakes. I decided not to add vanilla fish because they are notoriously laggy mobs and we really don't need any more of that in TF lol. I've been brainstorming biome reworks a lot lately and I have some ideas for custom fish and plants. Tbh this may have actually started my brainstorming sessions for new biome stuff, so thank you for that! Im gonna close this as things for this are actively being worked on but I'm gonna go in a bit of a different direction than simply adding the vanilla things.
