### ISSUE TITLE
Modded shears do not produce leaf drops

### ISSUE THREAD

**Issue by Seth0067** [TeamTwilight/twilightforest#1093]
Forge version: 36.1.4
Twilight Forest version: 4.0.426
Link to crash log: n/a

Steps to reproduce:
1. Load a game with TwiForest and a mod that provides shears (Botania and Cyclic in this example)
2. Craft shears from a mod (used flint shears from Cyclic and living wood shears via Botania)
3. Go to Twilight Forest dimension and hit Twilight Oak leaves with modded shears.

What I expected to happen:
Twilight Oak should drop Twilight Oak leaves, etc.

What happened instead:
No drops are provided

**Comment by GizmoTheMoonPig** [comment]
can you confirm this still happens in the 1.17 versions? If it does i'll look into a fix for it. Not really sure why it wouldnt be working tbh

**Comment by Kenpari** [comment]
I can confirm that this bug is still present in the 1.18 versions. I reproduced it with Twilight Forest 4.1.1025 on Forge 40.1.19 using modded shears from both Botania (two types) and Tinkers Construct (the Kama). Both modded shears work on leaves from other mods/vanilla (tested on Quark, Biomes O Plenty, and Decorative Blocks), but not with Twilight Forest leaves (tested three different types). Vanilla shears work fine. I also reproduced it with a minimal mod list of only Twilight Forest and Tinkers Construct + Mantle.
