### ISSUE TITLE
Hydra head is missing

### ISSUE THREAD

**Issue by JunEvergreen** [TeamTwilight/twilightforest#1103]
Forge version: ForgeOptifine(36.1.0)
Twilight Forest version: (Twilight Forest - MC 1.16.5 - 4.0.435)

Can anyone help me? I'll reply soon as i can

**Comment by TheOnlyMann** [comment]
opfitine have hard time rendering multipart enemies. This include hydra, Naga, and Snow queen.

tl;dr remove optifine.

**Comment by JunEvergreen** [comment]
> opfitine have hard time rendering multipart enemies. This include hydra, Naga, and Snow queen.
> 
> tl;dr remove optifine.

Im using a low end laptop which made me sad but is there possible for them to fix this? I'll wait till it releases! best wishes!

**Comment by thetaphobe** [comment]
you should try using Sodium Forge instead

**Comment by TheOnlyMann** [comment]
Go ask about optifine devs about fix for anything with optifine. Due to optifine being a closed source mod, other modders cant do anything about it even if one wants to fix all the problems. You're not going to get a fix from Twilight devs, cause they cant make one due to optifine being closed source.

**Comment by Tamaized** [comment]
Duplicate #1023
