### ISSUE TITLE
Game Crashes when attempting to activate a twilight forest portal as of latest 1.16.5 version

### ISSUE THREAD

**Issue by The-Bernician-Lamb** [TeamTwilight/twilightforest#1136]
Forge version: 36.1.23
Twilight Forest version: 4.0.464
Link to crash log: https://gist.github.com/NJL5390/2bca9800e1d4f9cc610c9fe352c9ad32

Steps to reproduce:
1. Start a new world with Twilight Forest Installed.
2. Build a twilight forest portal
3. Attempt to activate the portal by throwing a diamond in.
4. Game Crashes.

What I expected to happen:
The portal would activate and the game wouldn't crash.

What happened instead:
The game crashes whenever I try to activate a twilight forest portal. This bug also seems to prevent me from accessing that world ever again, as if I try to get back into the same world after the game crashed, the game just freezes on the loading screen until I use task manager to force it to close.

**Comment by Tamaized** [comment]
Can you show a full log, `/logs/debug.log` immediately after the crash (dont reboot before sending)

**Comment by The-Bernician-Lamb** [comment]
Here you go: https://gist.github.com/NJL5390/b10043d0fc4ace1ffd7a721c214c0768

**Comment by Tamaized** [comment]
Thanks
`[20May2021 21:03:29.684] [Render thread/ERROR] [net.minecraft.tags.TagCollectionReader/]: Couldn't load block tag twilightforest:portal/decoration as it is missing following references: immersiveengineering:hemp (from twilightforest-1.16.5-4.0.464-universal.jar)`
So we accidentally made a hard dependency on Immersive Engineering by mistake.. if you install IE it'll work otherwise we're working on a fix now

**Comment by Tamaized** [comment]
Should be fixed in 552748441e52a29cea7f1bd05ec397f3e1c915de
Will upload a build to curse shortly

**Comment by The-Bernician-Lamb** [comment]
Thank You! I appreciate the quick fix!
