### ISSUE TITLE
Fiery Pickaxe autosmelt does not work on nether gold ore

### ISSUE THREAD

**Issue by FloppaWithDrip** [TeamTwilight/twilightforest#1138]
Forge version: 36.1.0
Twilight Forest version: 4.0.467

Steps to reproduce:
1. Craft fiery pickaxe
2. mine nether gold ore

What I expected to happen: 
Mine the nether gold ore and get an ingot

What happened instead: 
It dropped nuggets

Also fortune with autosmelt does not work on the smeltable ores, but I was not sure if this is intended or not

**Comment by Niketats** [comment]
Why Nether gold ore should drop an ingot with auto-smelt? I think it shouldn't

**Comment by Tamaized** [comment]
Because vanilla does this??

**Comment by Niketats** [comment]
Huh? Vanilla Nether gold drop golden nuggets.

**Comment by Tamaized** [comment]
Not when you smelt the ore it doesn't

**Comment by TheOnlyMann** [comment]
..only if you get it as a ore, which requires silk touch?

**Comment by GizmoTheMoonPig** [comment]
I wrote this earlier on the discord, but the reason it doesnt work is because the fiery modifier changes drops, not blocks themselves. It should smelt into a gold ingot if you use silk touch. 
As for fortune, that probably wont happen, but I may look into it. 
Gonna close this since its not exactly valid to fix.
