### ISSUE TITLE
Add Chests and bookshelfs

### ISSUE THREAD

**Issue by Niketats** [TeamTwilight/twilightforest#1141]
Add Chests and bookshelfs made of Twilight Forest wood types, for example to work with "Variety chest/bookshelfs" Quark option. For now, chest and bookshelfs cannot be crafted when this option enabled.

**Comment by Andromander** [comment]
Rather than rely on mod compatibility, it would be best to put this as a suggestion for the main mod itself. It can always be present even without third-party mod, rather than having to twist and tie around compatibility when it isn't necessary.

~~I'd rather not close this as it is a viable suggestion for the mod, however it has been suggested to make it mod compat, which will unlikely happen.~~ EDIT: Changed to mod suggestion, all cool.

**Comment by saltyseadoggo** [comment]
I second this, and would also like to add the idea of replacing the generic chests in the various structures with ones made of Twilight Forest woods. Darkwood/towerwood chests in the dark tower, possibly mangrove ones in the labyrinth, varying types in druid huts, etc. Ones made from the magic woods could even do unusual things to their contents fitting their trees' effects, but this sounds a bit too much.

**Comment by Killer-Demon** [comment]
Wooden chest variants have been made and implemented. One bookshelf has been made and is slated for a dungeon rework with more most likely coming as they are needed.
