### ISSUE TITLE
Minecraft Version coming soon

### ISSUE THREAD

**Issue by Azar2477** [TeamTwilight/twilightforest#1168]
A new Minecraft version 1.17 is coming in June 8 2021.

If you wish to port Twilight Forest mod for 1.17 you can go ahead but there a more updates of Minecraft to come like 1.17.1 and 1.18 and you can wait for Forge 1.17.

**Comment by BurnutsGaming** [comment]
I hope they know after seeing the announcement from Mojang

**Comment by Andromander** [comment]
Yes...we know...why is this here? More importantly, why is it filed on our issue tracker at all? This is not alien to us in the slightest.

**Comment by BurnutsGaming** [comment]
> Yes...we know...why is this here? More importantly, why is it filed on our issue tracker at all? This is not alien to us in the slightest.

Thanks

**Comment by TheOnlyMann** [comment]
what

**Comment by Drullkus** [comment]
I appreciate the willingness of giving us a heads up about newer versions. We the developers are avid fans of Minecraft as well and we’re always monitoring new content added in snapshots.

If you’re thinking we weren’t aware of the 1.16 update because of our delayed release, that’s because 1.16 changed the fundamental way World Generation was put together. This required many months of re-designing systems on our end after months of deciphering the World Generation systems.

The issue tracker is also not the place for these types of tickets. If you have a bug or a feature suggestion for the game, then you’re in the right place. But otherwise memos don’t belong on our GitHub Tracker.

If you have any further concerns, feel free to join our Discord Server.
