### ISSUE TITLE
Crash with immersive engineering (when typing in search of applied energistics pc)

### ISSUE THREAD

**Issue by FlashFyreMods** [TeamTwilight/twilightforest#1169]
Forge version: 36.1.4 and 36.1.24
Twilight Forest version: 4.0.482
Crash log: https://pastebin.com/QQGQud9u

This occurs when typing in the search bar of an applied energistics pc. Crashes client when on server.

Sorry for wasting your time if immersive engineering is the root cause of this. (I also made an issue on its github)

**Comment by GizmoTheMoonPig** [comment]
This is fixed here on the github, so you have 2 options:
1. Download the latest dev build and use that instead
or:
2. downgrade immersive engineering to an older version
In a newer version of IE, they changed the location of a certain method I use for shader coloring. Its technically our fault, but its fixed now. We'll probably push a new TF build soon for people so they can use the beta rather than the dev build.

**Comment by GizmoTheMoonPig** [comment]
alright, I uploaded a new build to curseforge which contains the fix. So just update TF to the new beta and all will be good. Gonna close this since I know the fix works, as someone else has tested it before.

**Comment by FlashFyreMods** [comment]
Dope, thanks for the quick response :)
