### ISSUE TITLE
[1.16.5] World border affects the Twilight Forest dimension

### ISSUE THREAD

**Issue by ShortCircuit908** [TeamTwilight/twilightforest#1174]
Forge version: 1.16.5 - 36.1.24
Twilight Forest version: 1.16.5-4.0.482

Steps to reproduce:
1. Set world border in overworld to some value (10000 used)
2. Change world border center point in overworld

What I expected to happen: World border would not affect Twilight Forest or would be the same in both the overworld and forest dimension.

What happened instead: The entirety of the Twilight Forest is considered outside the world border. The red vignette appears on screen and it is impossible to break or place blocks. Setting the overworld world border to 30000000 centered at 0,0 places the Twilight Forest back "inside" the world border

**Comment by Tamaized** [comment]
We also use a world border value of 10000 on our official server and had no issue like this, changing the center offset might be what's causing issues hmm..

**Comment by Drullkus** [comment]
Correct, setting world border center is exacerbated by the dimension scaling. ~~So naturally this problem would happen in the nether too. Sounds like this bug should be reported to Mojang, not us~~ I've verified this problem happens to the Nether as well, [so this is a Mojang problem (here's their bug tracker)](https://bugs.mojang.com/projects/MC/summary).

The issue lies at Dimensional Scaling, that the Nether is `1:8` the scale of OW, the OW is `1:1` (with itself, naturally, and TF is 8:1 with OW, and `64:1` to the Nether. So if the border center is at `1, 1` in the OW, then it'll be at `0.125, 0.125` in the Nether, and `8, 8` in the TF. However you can still expect the border diameter to remain consistent.

Setting world border to 0, 0 otherwise maintains consistency across all worlds.

If you end up reporting this bug to [Mojang's Jira](https://bugs.mojang.com/projects/MC/summary) please link it in here and I'll give it an upvote
