### ISSUE TITLE
Boss Render Bugs+Worldgen Bug

### ISSUE THREAD

**Issue by banz3369** [TeamTwilight/twilightforest#1177]
Forge version: 1.16.5 - 36.1.24
Twilight Forest version: 1.16.5 - 4.0.490

Steps to reproduce:
1. enter the dimension and check them out

What I expected to happen:
Things work normally i guess
What happened instead:
1. Naga only has a head
2. Hydra missing all heads
3. Snow Queen missing the ice cloud
4. Hollow hills have nothing inside
5. firefly_forest biome is empty
![2021-06-12_17 25 48](https://user-images.githubusercontent.com/53364489/121772000-5588c080-cba5-11eb-8f03-cfd80625be85.png)
![2021-06-12_17 24 56](https://user-images.githubusercontent.com/53364489/121772007-66393680-cba5-11eb-9d3d-3661f3a33c31.png)
![2021-06-12_17 23 55](https://user-images.githubusercontent.com/53364489/121772016-7e10ba80-cba5-11eb-9409-9548ec5c6b5f.png)
![2021-06-12_17 23 29](https://user-images.githubusercontent.com/53364489/121772095-eeb7d700-cba5-11eb-90ed-004da35f375c.png)

**Comment by TheOnlyMann** [comment]
first 3 problems derive from optifine, rest seems to be a bug, do you have other mods other than optifine?

**Comment by banz3369** [comment]
> first 3 problems derive from optifine, rest seems to be a bug, do you have other mods other than optifine?

DiagonalFences  DoggyTalents  gravestone  Hwyla  JEI  mcw-bridges  mcw-fences  Patchouli  StorageDrawers  tablechair
that's all

**Comment by Andromander** [comment]
1, 2, and 3 all sound like issues with Optifine. This is something we cannot fix except for a warning on the start screen stating that bugs like this will happen and only they can fix.

4 is definitely a bug, though it appears to be random when this happens.

5 is what happens when a mod that adds additional block states - such as Diagonal Fences - is added to a pack. Unfortunately, those mods are adding block states "dangerously" and can break datapacks, which is where worldgen is handled, too. We cannot do anything about this, either.

I would like to note that separate tickets should be opened for each bug. It's much easier to track; this issue has 4 unresolvable issues and 1 confirmed issue, however it would be confusing to keep this open as it implies he other 4 are related, which the are not in this instance.
