### ISSUE TITLE
Biomes Need Rework

### ISSUE THREAD

**Issue by Blunder-G** [TeamTwilight/twilightforest#1202]
Forge version: Doesn't matter

Twilight Forest version: Twilight Forest - MC 1.16.5 - 4.0.490

As far as I've heard, the structures are being redesigned. This is beautiful. But to me structures are not the problem, the main problem is dimension and biomes. 

**What's annoying?** 

Biomes don't feel like stepping into a new world. The Nether has a style of its own. End's too. But Twilight forest looks like Overworld version 2.

Trees don't  look interesting. They don't have a unieqe formation. They're also EXTREMELY big, have no detailed formation, and look so pointless to explore.

The ground is covered with grass. I don't see any new plants, the water doesn't even have a color characteristic of its own! It's like the overworld is covered with more beautiful bosses and creatures. Nothing more, nothing less...

**What shoul we do?**

MAYBE, add a new member to your team. Adding someone who does this kind of work and can bring a whole new world could add a new flavor to team!

A new world requires new blocks and textures. For example, instead of the grass block on the ground, you can add a kind of grassy soil called "Twilight Sparkles" (I made up the name, you can find a better one)

Special worldgen! Perhaps giant star-like structures flying in the sky! A biome full of them. These stars should even have their own blocks! Something like "Starock", for example.

**Long Stroy Short...**

Twilight Forest offers exciting adventures. Creatures are AWESOME. The boss battles are EXCITING. But exploring isn't all that fun. Twilight Forest needs a rework. It must be a world like no other...

**Comment by GizmoTheMoonPig** [comment]
During the port to 1.16, everything about the dimension got overhauled and redone since we had to switch to a new system. Even though we tried to focus on porting directly from 1.12, we still tried to spruce up the dimension a bit and make certain things more unique. We have our own custom trees and plants already. Canopy, mangrove, darkwood, hollow oaks, rainbow oaks, mayapples, fiddleheads, and various other decorations can be found throughout the forest, and I'm sure more decoration is planned with the structure reworks. There are still some plants, such as the clover patch, that still go unused and could be integrated in some way in the future. We already have quite a bit, but I do understand where you're coming from. The dimension feels very vanilla, but that's kinda the point. Making crazy changes like new grass and things like that will stray away from the idea of it being a vanilla expansion. However, I do agree that maybe the dimension needs to be a bit more unique, and I would really love to add some more decoration to the dimension. 

Now, to address some points in your issue:

> Trees don't look interesting. They don't have a unique formation.

This simply isn't true at all. All the trees except for twilight and rainbow oaks have unique generation and all use our own blocks. Each biome has its own trees that make the biome feel more unique than others. Swamps are the only biome that have mangrove. Similarly, you can only find darkwood in the dark forest biomes. Rainbow oaks can only be seen in the enchanted forest. We also have 4 special saplings that can be found in those towering oak trees that all have unique functions and shapes. Canopy trees are all over the place, but some biomes have unique versions of the tree. Large, unique shaped mushrooms can be found both mushroom forest versions. The firefly forest has canopy trees that have firefly jars hanging from them, and the spooky forest is filled with dead versions. 

>  They're also EXTREMELY big, have no detailed formation, and look so pointless to explore.

I'm assuming in this point you're talking about hollow oak trees. These trees are meant to be huge, and its rather hard to detail them because of their size. In these trees, you can often find a small dungeon or 2 that contains some nice loot, and can even contain the saplings I talked about earlier. I think it would be nice if these large trees could get a bit more detailed in the future, but this isn't a priority as its pretty difficult to get it looking nice with changes. 

> The ground is covered with grass. I don't see any new plants, the water doesn't even have a color characteristic of its own! It's like the overworld is covered with more beautiful bosses and creatures. Nothing more, nothing less...

As I said earlier, we add quite a few new plants, with more to hopefully come in the future. Along with having flowers all over, we have mayapples mixed in with the grass all over. Moss covers fallen logs, creating an overgrown feeling. Fiddleheads can be found in the enchanted forest. Caves are filled with torchberry plants and root strands to make them feel more earthy. Mushglooms are found in the dark forest and the mushroom forest. Thorns, while also being a barrier, are their own unique plant and even have special leaves and roses on them. Not to mention all the ruined structures and other decorations you can find on your journey around the dimension. The issue with adding more things is it may feel too crowded, and that wouldn't be a good thing either. I think we have a good mix of things around to add more life, but more things may be added in the future, no guarantees though. 

Apologies for the text wall, but this is definitely something I'm passionate about too. I feel like decoration and ambience are EXTREMELY important when making a whole other world. I always discourage people flying through the dimension because I want them to fully experience the mood of the whole mod, not just the bosses. I would add a lot of new stuff if I could too, but hey, I have to think about the original intention of the mod. I hope this provides a bit of insight on what we aim for with the mod and what we're trying to do about things like this.

**Comment by Andromander** [comment]
I had this issue labelled as a Suggestion due to the nature of it not being a bug report. However, due to the nature of the ticket, it has come to my attention that the report does not have the substance of a Suggestion and more just a list of grievances and a degree of misunderstanding.

I won't get into the detail of the whole ticket, but I want to touch upon this:

>MAYBE, add a new member to your team. Adding someone who does this kind of work and can bring a whole new world could add a new flavor to team!

This statement is extremely rude and fails to understand how this mod works.

We have new team members; I joined the team to port this to 1.16, Gizmo above joined after me to help out. We have team members who scrutinise ideas until they are exactly what Twilight Forest needs and not just a bunch of My Little Pony name references in blocks. We are not looking people who don't know how to code, or don't know what makes Twilight Forest what it is, only people who know how to code and understands why this mod is the way it is.
We don't just add people because it's a fun party time; I've worked in teams where the members were added based on wanting to have the Developer role under their name, and what happened is they fall into complete disarray and unable to work because nobody could actually develop the mod.

Worldgen overhauling has been a consideration for this mod for a long while. There has been not enough manpower to get to that stage just yet because of the lack of energy, lack of members capable of coding and understanding how the mods work. We aren't looking to add a bunch of ideas people to the team; trust me on this, I know exactly what happens when that is the only kind of people brought on when there is a lack of people to code.

As I have already stated earlier, there's not much substance here to say this is a Suggestion. Generally improving how worldgen should be done in future updates is already in discussion behind the scenes, and as such, this issue will be closed due to not bringing much new to the table.
