### ISSUE TITLE
Trees are not spawning under Giant's Clouds

### ISSUE THREAD

**Issue by BurnutsGaming** [TeamTwilight/twilightforest#1207]
Forge version: 36.1.65
Twilight Forest version: 4.0.511
Link to crash log:

Steps to reproduce:
1. Go to the Twilight Forest and find the Giant's Clouds.

What I expected to happen: There should be trees spawning under there.

What happened instead: Trees would just spawn at the Giant's clouds and wont spawn under.

**Comment by BurnutsGaming** [comment]
Accidental early submit. Sorry.

**Comment by GizmoTheMoonPig** [comment]
It was like this in 1.12, so it'll most likely stay this way in 1.16. The reason this happens is because the clouds are generated on the actual chunk generation itself rather than feature placement. Trees come in after the clouds are generated, and since the clouds blocks skylight, it doesnt allow trees to grow there. Its probably better to keep it this way so people can easily grow beanstalks without colliding into other trees.

**Comment by BurnutsGaming** [comment]
Ok.
