### ISSUE TITLE
open minecraft versions Lower than or equal to 1.4.7 are all black screen

### ISSUE THREAD

**Issue by MW1Z** [TeamTwilight/twilightforest#1222]
Forge version: forge-1.4.7-6.6.2.534
Twilight Forest version: Twilight Forest - MC 1.4.7 - 1.16.3
Link to crash log: 

Steps to reproduce:
1. open the game
2. Black screen after mojang logo

What I expected to happen:Enter the game

What happened instead:Keeps black screen

**Comment by Tamaized** [comment]
All the jars recovered worked back in the day so the only thing I can say is the install process is done wrong. Keep in mind these were jar mods back before 1.6 and may not just work with a mods folder

**Comment by Andromander** [comment]
The name of the issue seems to be confusing as it says "Lower than or equal to 1.4.7" despite the version range in the issue ticket specifying 1.4.7 - 1.16.3; versions later or equal to 1.4.7.
In any case, I'm closing this as it pertains to a version that not only is outdated, but we also lack the source code for it for much older versions. If this issue does present itself in supported versions, feel free to make a new issue ticket, preferably with a client log.

**Comment by Tamaized** [comment]
1.16.3 is the mod version
