### ISSUE TITLE
Update to 1.12

### ISSUE THREAD

**Issue by fmohican** [TeamTwilight/twilightforest#125]
hello,
can u make a build for 1.12 ? 

Thanks you.

**Comment by Andromander** [comment]
At this moment, the mod will be ported to 1.11.2 for now. Once porting for this version is complete, a port for 1.12 will go underway later, since it is easier to port from 1.7.10 to 1.11.2 than 1.12. It has also been mentioned in the Discord channel that 1.12 will be released when Forge 1.12 becomes available. Status for the current port is at around 80%-90% complete

**Comment by fmohican** [comment]
Thanks you.

**Comment by Drullkus** [comment]
Saw this issue while surfing issues, yes TF is now 1.12 and 1.12 only
