### ISSUE TITLE
Vanilla mobs should attack certain TF mobs

### ISSUE THREAD

**Issue by GizmoTheMoonPig** [TeamTwilight/twilightforest#1303]
Wolves should target dwarf rabbits, forest squirrels, and bighorns (need to ASM the predicate)
Cats should target ravens, dwarf rabbits, forest squirrels, and tiny birds (can be done by adding a goal)
Foxes should target dwarf rabbits and forest squirrels (uses a predicate, but is different than the wolf)

If anyone has more suggestions of mob interactions please write them here

**Comment by saltyseadoggo** [comment]
Since they seem like an aggressive and reclusive bunch, redcap goblins/sappers could attack villagers and pillagers/vindicators/evokers on sight, and the illagers could attack them in return. I may be completely misinterpreting the pseudolore here; lemme know if this isn't the intended characterization of the redcaps.

I don't actually agree with this anymore, but I'll leave it here for you to form your own opinion.
