### ISSUE TITLE
weird thorn gen

### ISSUE THREAD

**Issue by VilligerKing** [TeamTwilight/twilightforest#1349]
### Forge Version

37.0.82

### Twilight Forest Version

4.0.776

### Steps to Reproduce

go to thorn place n search for "the funny"

### What You Expected

Connecting thorns and no green thorns in the thornlend

### What Happened Instead

weird

### Additional Details

screene lol

[
![image](https://user-images.githubusercontent.com/82680956/137431925-aeb8bd32-d033-46a8-9580-d2d6c550196a.png)
](url)

also was on server, cords in screene

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).

**Comment by GizmoTheMoonPig** [comment]
the floating green thorns are a side effect of another bug, which is caused by the castle attempting to go outside what it considers its bounding box. It seems like an overgrown tower attempted to generate there but couldn't because of this issue. I'll redirect this to #1054 as it addresses the broken structures, it may be a while before we can actually get this fixed though
