### ISSUE TITLE
i have a problem

### ISSUE THREAD

**Issue by legendary1622** [TeamTwilight/twilightforest#1372]
### Forge Version

36.2.8

### Twilight Forest Version

4.0.546

### Steps to Reproduce

using the mod he tried to create a new world and it appears to me that the world is open in experimental mode and that it is very likely to be corrupted

### What You Expected

I thought it was because of the mod version

### What Happened Instead

I keep getting the same notice even though I had changed the version of the mod

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).

**Comment by Andromander** [comment]
There exists a config option to turn off the vanilla feature...

**Comment by Drullkus** [comment]
Known. Ignore the screen by clicking the "I know what I'm doing!" button.

![image](https://user-images.githubusercontent.com/5010174/139774713-62c97690-6e7b-451f-87f3-05c723765653.png)

Since you're on 1.16 and not in later versions: Go download this mod if you hate the "Here be Dragons" so much <https://www.curseforge.com/minecraft/mc-mods/shutup-experimental-settings>

In 1.17 and beyond we have an option in `twilightforest-client.toml` labelled `disableHereBeDragons` that disables this screen and lets you straight into the game.
