### ISSUE TITLE
How to disable this message?

### ISSUE THREAD

**Issue by ghost** [TeamTwilight/twilightforest#1374]
### Forge Version

36.2.8

### Twilight Forest Version

1.16.5-4.0.546-universal

### Steps to Reproduce

1. Add twilight forest mod
2. Load minecraft

### What You Expected

Hi, i can't find option in config file what can disable this message when minecraft start
http://prntscr.com/1yh8s2y

### What Happened Instead

The message does not turn off

### Please Read and Confirm The Following

- [ ] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).

**Comment by Drullkus** [comment]
`disableOptifineNagScreen` in client config

**Comment by GizmoTheMoonPig** [comment]
> I have confirmed this bug can be replicated without the use of Optifine.

...why exactly did you check this? This can only be seen with optifine on. 
Also, the screen literally says it can be turned off in the config. If theres a screen like this that shows up, perhaps you should read it instead of coming over here to ask a question that the screen itself already answers.
