### ISSUE TITLE
Set harvest levels for your blocks

### ISSUE THREAD

**Issue by saltyseadoggo** [TeamTwilight/twilightforest#1389]
Gizmo uncovered on the Discord that TF doesn't set harvest levels for its blocks, which is causing the block and chain to behave oddly, and requested that I open this issue as a reminder. Fix it, Giz!

**Comment by GizmoTheMoonPig** [comment]
ok I actually learned that the block and chain being weird was because of explosion resistance levels with TF blocks, which were all wonky and much higher than they should have been. Since TF has never had the need for harvest levels I dont think i'll be adding any in, but I have fixed the block and chain issue.
