### ISSUE TITLE
Enable Dim Validation

### ISSUE THREAD

**Issue by SheReyy** [TeamTwilight/twilightforest#1395]
There's this block of code in the mod, which I need.
 
    ```// Find a different way to validate if a world is passible as a "Twilight Forest" instead of hardcoding Dim ID (Instanceof check for example)
    //public static final RegistryKey<World> twilightForest = RegistryKey.getOrCreateKey(Registry.WORLD_KEY, new ResourceLocation(TFConfig.COMMON_CONFIG.DIMENSION.twilightForestID.get()));```

I don't know why it is commented, but is there any chance you can enable this? And if not, how could I validate this? I tought of lots of options, but none really did the job for me.

**Comment by Tamaized** [comment]
You know you can just create that key yourself right.
Besides, we check via the chunk generator class type now, but there is a string based check from the config as well if need be
https://github.com/TeamTwilight/twilightforest/blob/1.17.x/src/main/java/twilightforest/world/registration/TFGenerationSettings.java#L149-L155

**Comment by SheReyy** [comment]
I can just create it and it works? 0_0 Lol, I'll try that, thx a lot.

**Comment by Drullkus** [comment]
Unless you ABSOLUTELY need to check if it's a Twilight World, use `usesTwilightChunkGenerator` since it tells you if it's *a* Twilight World because that's possible. This is more ideal unless you're doing portal related stuff then yes you'll want to use `isStrictlyTwilightForest`. I'll be commenting on those methods to make this distinction clearer

**Comment by Drullkus** [comment]
Check out 51a90bf6acc54ad1c10e9f333ecbb149fbf3db45, I added a new method, several comments explaining usages, and renamed a method or two
