### ISSUE TITLE
Hitboxes on big mobs hard to hit.

### ISSUE THREAD

**Issue by Pantheris2019** [TeamTwilight/twilightforest#1431]
### Forge Version

14.5.2855

### Twilight Forest Version

3.11.1021

### Steps to Reproduce

1. fight a large boss
2. find that the hitbox is really disproportionate to the size of the boss.
3. done

### What You Expected

Be able to hit any part of the boss when able to see it in HWYLA to inflict damage.

### What Happened Instead

No damage at all when struck anywhere else but a small hitbox on the boss itself.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
which bosses are you having trouble hitting? The only one that seems to have a problematic hitbox is the Ur-Ghast, since you can really only hit that one from the bottom. You're only supposed to really be able to hit it from the bottom anyway, since the intended way to fight it is to pull it down with the ghast traps. 
From my testing all the other boss hitboxes seem to work as intended. You hit the boss; it damages it. Let me know which ones are giving you trouble and tell me where you're trying to hit it from, and I can try to help.

**Comment by Pantheris2019** [comment]
the Ur-Ghast literally has to be hit by standing in the bottom center of its face and the only way to reliably beat it is by using the ghast traps, which I do assume is the _partly_ intended way to fight it, but instead ends up causing frustration when you try to hit it with weapons while doing so.

**Comment by GizmoTheMoonPig** [comment]
yeah, that's intended. You're supposed to use the ghast traps to yank it out of the sky, and once its down that's really the only place you can hit it. The traps are the fully intended way to fight it when in tantrum mode, the other bit is knocking back the fireballs, which I've found through playing seems to work alright.
The main issue with the ur-ghast is that its ENORMOUS. Making a giant hitbox properly work isn't easy, and that isn't necessarily our fault. The hitbox is positioned the way it is so players can fight it the way the fight was intended, and unfortunately the tradeoff for that was making it have a jank hitbox. I can play around with it and see if I can get better coverage but I can't promise anything will change. Hope you understand
