### ISSUE TITLE
hydra head error 1.17.1

### ISSUE THREAD

**Issue by Gearsofwar6145** [TeamTwilight/twilightforest#1497]
### Forge Version

37.1.1

### Twilight Forest Version

4.0.943

### Client Log

https://gist.github.com/Gearsofwar6145/196cc61c71e4e6c1caa58338b66535a6#file-latest-log

### Crash Report (if applicable)

https://gist.github.com/Gearsofwar6145/26da92e0d6283b5b34f17c508830679c#file-crash-2022-05-30_18-29-31-client-txt

### Steps to Reproduce

load launcher 
try to open minecraft with forge 1.17.1
then i get a crash report saying that the hydra head canna load "Error: java.lang.IllegalArgumentException: No model for layer twilightforest:hydra_head#main)

### What You Expected

to play modded minecraft

### What Happened Instead

it crashed

### Additional Details

im srry this is my first time doing one of these

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
One of your mods crashed earlier during registration. TF didnt crash here.
`Caused by: java.lang.UnsupportedClassVersionError: net/darkhax/enchdesc/EnchDescForge has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 60.0`
