### ISSUE TITLE
[Suggestion] More Interesting Snow Queen Castle

### ISSUE THREAD

**Issue by mateidragony** [TeamTwilight/twilightforest#1503]
### The Suggestion

The current castle where the snow queen lives is a bit bland. I'm a massive fan of how unique and interesting both the Ur-Ghast boss battle and castle are and I would love to see that same level of detail and uniqueness added to the Snow Queen Castle. I can't think of any specifics, this suggestion is more of an open-ended idea to get the ball rolling

### Why Should It Be in the Mod?

The mod is already amazing and probably one of the best mods in Minecraft and this change would just spruce up a pretty simple boss fight/ dungeon

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by GizmoTheMoonPig** [comment]
The aurora palace already needs to be reworked, it breaks more and more every update and we're planning on migrating all structures to NBT anyway. If the naga courtyard and the WIP lich tower are anything to work off of, we'll be sprucing the structure up during migration. Closing as we are actively brainstorming ideas for the palace internally since we also agree the aurora palace is very bland and desperately needs more.
