### ISSUE TITLE
[1.19] Breaking infested towerwood with silk touch does not spawn a borer

### ISSUE THREAD

**Issue by EvergreenSystems** [TeamTwilight/twilightforest#1561]
### Forge Version

41.0.35

### Twilight Forest Version

4.2.1163

### Steps to Reproduce

1. Break an infested towerwood block with a tool enchanted with silk touch

### What You Expected

I expected to either pick up an infested block or for it to spawn a borer per normal behavior

### What Happened Instead

The broken block did not drop anything, and a borer did not spawn. This does not match up with vanilla behavior for infested blocks: if infested stone or similar is broken with a silk-enchanted tool, the silverfish is still spawned and immediately aggros at the player (per the Minecraft wiki). Additionally, the block broken will still drop itself, for example infested stone would both spawn a silverfish and drop a stone block. If the infested towerwood is meant to be analogous to the vanilla block, the borer should spawn and attack the player, and either infested or normal towerwood should drop as an item.

### Additional Details

Discovered on the TF testing server

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
looking through the code of infested towerwood vs infested stone, we handle mob spawning the same way: if there's silk touch involved, nothing will spawn. Not sure where the wiki got the info you stated from, but it's wrong. I like the idea that infested towerwood should drop nothing, tbh. It should never drop the block itself, and I don't think it should drop normal towerwood because the infested version looks like rotted wood. The wood would just dissolve no matter how you attempt to harvest it

**Comment by EvergreenSystems** [comment]
Ah yeah I did misread the wiki, but I still feel its odd that absolutely nothing happens when you go though the effort of getting a silk-touch tool out to the dark tower

**Comment by Drullkus** [comment]
It is odd, but it stays consistent with vanilla
