### ISSUE TITLE
Diamonds will disappear when thrown into water

### ISSUE THREAD

**Issue by Hakoyu** [TeamTwilight/twilightforest#1575]
### Forge Version

40.1.60

### Twilight Forest Version

4.1.1184

### Steps to Reproduce

If you throw a diamond into the water that is not filled with flowers, it will still disappear.

### What You Expected

Diamonds will only disappear in the 2*2 waters surrounded by flowers

### What Happened Instead

Because I also installed Applied Energistics 2 and Lazier AE2, some synthesis requires throwing diamonds into the water.
But when I throw the diamonds into the water with the other synthesis materials, only the diamonds disappear and the synthesis is not completed.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
unable to reproduce this with just Twilight Forest. Diamonds float in the water as normal if the portal isn't valid. 

A quick look over the code also shows that the diamond will only be consumed if the portal successfully forms, so I dont think this is our doing. This seems like it would be some other mod consuming the diamonds. If you remove TF and the issue is resolved, then I'll look into this further.

**Comment by Hakoyu** [comment]
Thanks for the reply, I'll try to line up other mods
