### ISSUE TITLE
Block Strength III doesn't break mazestones

### ISSUE THREAD

**Issue by SodiumZH** [TeamTwilight/twilightforest#1600]
### Forge Version

40.1.68

### Twilight Forest Version

4.1.1184

### Steps to Reproduce

1. Enchant a Block and Chain with Block Strength III book
2. Try hitting the wall of Labyrinch (mazestones) with it

### What You Expected

Mazestones should be broken
(Description showed that Block Strength I will break mazestones)

### What Happened Instead

Nothing is broken

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
Intended. 
In 1.17 it was allowed to, but we realized how broken that was since you can get to the stronghold before the labyrinth, so I excluded it from being broken in 1.18

**Comment by SodiumZH** [comment]
> Intended. In 1.17 it was allowed to, but we realized how broken that was since you can get to the stronghold before the labyrinth, so I excluded it from being broken in 1.18

Could you please tell how the Block Strength works in 1.18 and 1.19? I'm working on the Chinese wiki of TF now.

**Comment by GizmoTheMoonPig** [comment]
In 1.18 it works the same as it did in 1.17, I just excluded mazestone from breaking. 
In 1.19 the block and chain was reworked quite a bit. It now doesn't break blocks by default and we removed all but 1 enchantment which got a repurpose. Destruction now allows it to break blocks, and goes up to level 3. Each tier allows it to break stronger blocks. Level one allows you to break blocks that need a wooden tool, level 2 is stone, and level 3 is iron. TF blocks now also have harvest levels. Since mazestone is diamond tier now you can't use the block and chain to break the blocks. Same thing goes for a couple other structure blocks, such as aurora blocks and castle blocks

**Comment by SodiumZH** [comment]
> In 1.18 it works the same as it did in 1.17, I just excluded mazestone from breaking. In 1.19 the block and chain was reworked quite a bit. It now doesn't break blocks by default and we removed all but 1 enchantment which got a repurpose. Destruction now allows it to break blocks, and goes up to level 3. Each tier allows it to break stronger blocks. Level one allows you to break blocks that need a wooden tool, level 2 is stone, and level 3 is iron. TF blocks now also have harvest levels. Since mazestone is diamond tier now you can't use the block and chain to break the blocks. Same thing goes for a couple other structure blocks, such as aurora blocks and castle blocks

Thank you for your kind reply. In 1.19, does it mean that the Destruction III-enchanted Block and Chain behaves like the non-enchanted one in 1.17, without expanding the block-breaking range?

**Comment by GizmoTheMoonPig** [comment]
Correct
