### ISSUE TITLE
[Suggestion] Allow mushrooms to be planted anywhere in the Twilight Forest dimension

### ISSUE THREAD

**Issue by MarioSMB** [TeamTwilight/twilightforest#1603]
### The Suggestion

Mushrooms seem to break when generated around portals inside the Twilight Forest, it might be nice to allow them to be planted anywhere within the dimension since there's no sunlight to disrupt their growth.

### Why Should It Be in the Mod?

It would fit the dimension quite well - there are giant mushrooms everywhere already, there is no sun and there's currently an issue where the mushrooms around the portal will break when loading in, this would resolve it without needing to remove mushrooms from the portal's fairy ring.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by GizmoTheMoonPig** [comment]
Mushrooms can already be planted anywhere, the only reason they break around portals is because portal blocks emit light. We cant really change how mushrooms work with light levels

**Comment by MarioSMB** [comment]
The portal generates with plants that are broken by the portal? That sounds like a bug, one with high visibility as it's the first thing one sees upon entering the dimension.  
I can file a separate report for that if preferred, in my testing mushrooms were not able to be planted anywhere hence the issue in suggestion form.

**Comment by GizmoTheMoonPig** [comment]
again, we can't control how mushrooms work with light levels. I'm very hesitant to remove mushrooms from spawning around the portal because they've been there since the portal was added to the mod. 
About the mushroom placement: turns out you're right, they can't be placed anywhere. Every time I tried I was just under a tree which allowed placement. Mushrooms check for a sky light level of 13, so tree leaves covering the sky allows for them to be placed more often in TF than in the overworld. I wish we could make them placeable anywhere but changing how vanilla code works is a huge nono for us.

**Comment by MarioSMB** [comment]
That's understandable regarding needing to change vanilla code for placement to function.  
The generation issue is another matter, but it could be worth discussing among the team since it's not like the mushrooms can be seen there as they break immediately.

**Comment by Tamaized** [comment]
Nah

**Comment by MarioSMB** [comment]
I’d just like to point out that bugs aren’t nostalgic.  
But with that said I’ll be leaving this topic alone.
