### ISSUE TITLE
[1.19.2] Invisible entities when mod is installed 

### ISSUE THREAD

**Issue by ffuentesm** [TeamTwilight/twilightforest#1629]
### Forge Version

43.1.16

### Twilight Forest Version

4.2.1392

### Client Log

https://gist.github.com/ffuentesm/9c74501f7a81fa580c4d2204f173d55c

### Steps to Reproduce

Install twilight forest mod
Join a world
chests, items drops, mobs, are all invisible
if you re join the world without the mod installed, the entities are visible again.and 

### What You Expected

The entities should be visible even with the mod installed

### What Happened Instead

with the twilight forest mod installed, chests and other entities are invisible

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Andromander** [comment]
Honestly, the logs show far more problems than just invisible entities, but it's hard to tell because there are far too many errors to go through, especially because I can see that the datapack for Twilight Forest isn't loading; something that shouldn't be happening as Forge handles mod datapacks.

We're going to need more info, such as other mods and whether this happens with only TF.

May also be worth updating the mod as it has since been updated.

**Comment by Tamaized** [comment]
Does this occur on the latest version? Does it occur without any mods?
