### ISSUE TITLE
corruption with Biomes o'plenty

### ISSUE THREAD

**Issue by MrWachu** [TeamTwilight/twilightforest#1666]
### Forge Version

1.16.5 36.2.39

### Twilight Forest Version

4.0.870

### Steps to Reproduce

I don't know how it happened

### What You Expected

The Twilight Forest dimension merged with the overworld.

### What Happened Instead

The biome where I built my house (overworld) became the Fire Swamp biome

### Additional Details

![image](https://user-images.githubusercontent.com/116408940/197306884-74c035b8-21b6-4631-9c9b-0801221774e8.png)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Andromander** [comment]
This behaviour of Biome shuffling is a result of when one mod does not register biomes correctly, causing biome IDs to get shuffled around and getting displaced into other biomes under certain conditions. However, this has been fixed on our end since the first release of the mod, so this is likely a BoP issue if they are not registering biomes properly.
