### ISSUE TITLE
ColorHandler crashed when construct the mod

### ISSUE THREAD

**Issue by shordinger1** [TeamTwilight/twilightforest#1723]
### Forge Version

1.12.2-Forge_14.23.5.2860

### Twilight Forest Version

twilightforest-1.12.2-3.11.1021-universal

### Client Log

<script src="https://gist.github.com/shordinger1/4d41558f5c85c9b081b6fa87ddf0d365.js"></script>

### Crash Report (if applicable)

<script src="https://gist.github.com/shordinger1/4d41558f5c85c9b081b6fa87ddf0d365.js"></script>

### Steps to Reproduce

crashed before i do anything in this game

### What You Expected

it seems that the graphic modles doesn't works correctly. the illegal argument may caused by other mods, maybe i need to find which one did that?

### What Happened Instead

nothing

### Additional Details

i installed the optifine before, but unstalled it after i read your notification.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Andromander** [comment]
We'd need the actual client log, the one provided in Client Log is just the crash report.

From what I can get at from here, there are two possibilities: the file for Twilight Forest got corrupted while downloading (easy fix, just download the mod again), or there is a different error that happened earlier and our mod was caught up in the crash.

To narrow down what mod might be causing this issue, you can do what is known as a Binary Search, where you take half the mods out of the list (make sure required libraries exist in the same halves) and test if they continue to crash the game with the report above. When you find the half that crashes, repeat this process until you have a couple mods left. To help, test if this crash happens with only Twilight Forest to check if it is a result of another mod error or if the file got corrupted.

I will note that 1.12.2 is no longer a supported version, but if you can provide some extra details such as the full log rather than just the crash and fewer mods, feel free to drop a comment and we can take a look.

**Comment by Tamaized** [comment]
I'm not sure why the file is missing but 1.12.2 is no longer supported.
