### ISSUE TITLE
[Suggestion] Uncrafting table bottoms should use timewood planks

### ISSUE THREAD

**Issue by kodadacod** [TeamTwilight/twilightforest#1811]
### The Suggestion

Pretty self-explanatory, the bottom of uncrafting tables should use timewood planks instead of jungle planks

### Why Should It Be in the Mod?

Having the bottom use timewood would be more consistent with the rest of the uncrafting table as the planks used on the side texture are timewood

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by jodlodi** [comment]
This is an issue in regards to the JAPPA version of the Uncrafting Table, which has since been moved to a standalone resource pack that can be found [here](https://www.curseforge.com/minecraft/texture-packs/twilight-forest-jappa-pack). 
We have now returned to the classic textures of the mod, where the uncrafting table's texture is consistent.
