### ISSUE TITLE
Broken ru_ru translation

### ISSUE THREAD

**Issue by Proxwian** [TeamTwilight/twilightforest#1814]
### Forge Version

40.2.2

### Twilight Forest Version

twilightforest-1.18.2-4.1.1494-universal.jar

### Steps to Reproduce

1. Start singleworld or join server
2. See logs
3. See item translations

### What You Expected

ru_ru.json loading propely

### What Happened Instead

![image](https://github.com/TeamTwilight/twilightforest/assets/31781674/89968d21-ceb8-48f7-bab6-07a310ea3de9)

### Additional Details

With default ru_ru.json I can't even load datapack with translated version of this json in it. Mod always load default lang instead

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
this has been fixed in more recent versions with the transition to crowdin. If you want to fix this on your end you can simply use a resource pack. All you need to do is copy the lang file and remove the comma at the end of the line here: https://github.com/TeamTwilight/twilightforest/blob/1.18.x/src/main/resources/assets/twilightforest/lang/ru_ru.json#L1244
