### ISSUE TITLE
Reworking gear balance

### ISSUE THREAD

**Issue by DiamondWalker** [TeamTwilight/twilightforest#1833]
### The Suggestion

So far, I haven't really enjoyed "upgrading" my equipment. It is very disappointing getting to a dungeon only to find the gear there isn't as good as what I have, or, even worse, finding two pieces of armor are nearly identical and having to guess whether it's better to have slightly more defense, armor toughness, or protection enchants.

The first thing I would do is
**_REMOVE THE DEFAULT ENCHANTMENTS_**. They cause several issues:
-as mentioned above, with armor comparing defense and toughness is already almost impossible. Having different levels of enchantments on top of that makes it way too difficult to figure out if one set is better than the other.

-having enchantments be included with the item interferes with vanilla's enchantment mechanics. You can't use an enchantment table, nor can you apply enchantments that aren't compatible with the one that comes included. This is very annoying.

-it also causes issues with items obtained through other means. If an item is balanced around a certain enchantment, when that item spawns in chests with a different enchantment, it'll be unbalanced. Steel leaf armor found in chests is absolutely useless.

Instead of enchantments, I would 
**_GIVE THE GEAR UNIQUE ABILITIES THAT ARE PART OF THE ITEM ITSELF_**. For examples, look at the aether or the advent of ascension mods.

The last thing to do now is rebalance the stats themselves. I think the most important thing here would be to
**_MAKE THE "TIERS" SIMPLE_**. No more "I have +1 defense but you have +1 armor toughness". It's very confusing.

------------------------------------------------------------------------------------------------------------------------------------
The three things I've said are pretty vague and general, and twilight forest doesn't have a lot of room to mess around if it wants to stay balanced around vanilla, so I'll give an exact description of how I would balance the different sets:

-ironwood would have the same stats as iron, with the added ability to repair itself very slowly. However, it would have very low durability, maybe even lower than gold. If you rush head first into a dungeon or go on a huge mining expedition, they may break, but for all other purposes, they are the perfect way to avoid the hassle of fixing or replacing damaged items.

-the naga scale armor pieces would also have the same defense as iron, but its ability would be applying this defense to non-physical damage sources, such as magic, fire, and freezing. This would make it great for the lich tower, dark forest, or snow biome (see addendum*).

-the arctic armor could stay as it is, or could instead be a set with 20 defense but no toughness. It's a good set, but it wouldn't make sense making it comparable to diamond as you can get it right after the lich.

-the knightmetal armor set would have the same defense and toughness as diamond, but would have high knockback resistance, maybe even full immunity if wearing all the armor. This would make it a good general combat set that's also extra effective against ranged mobs (or on cliffs). Dunno about the tools, maybe they can stay as they are.

-the steelleaf gear would be an upgrade of the ironwood gear: same gimmick, higher stats. The armor would be about as good as the arctic set. Throw some enchants on this and you have a permanent set for your everyday needs.

-the phantom armor would be slightly worse than diamond and would keep its current ability. It may be a little weird making the armor that comes from the dungeon boss be weaker than the armor from the rest of the dungeon, but I think the ability is powerful enough to justify it.

-the yeti armor would be as strong as diamond, with the ability to grant protection against both types of "thermal" damage: fire and freezing. You may notice this would make it worse than the knightmetal armor, but I think this makes sense since the yeti armor just requires stepping into a cave and killing it while knightmetal is found in a huge dungeon and is rather grindy. The ability would still make it really good for the hydra, aurora palace (see addendum*), and even other dimensions, like the nether. You may also notice it would no longer be a counterpart to the fiery armor. I think this makes sense, too. Fiery armor not only requires a full dungeon, but also an extra biome and boss.

-dunno about fiery armor. As good as netherite, or even better. Should definitely be the best set for now, as it's the highest tier.

(*-to make the most of these abilities, there should be more sources of freezing damage, like the snow wolves' breath and the aurora palace mobs)

### Why Should It Be in the Mod?

I didn't see this before so I just wrote everything above, LOL. I hope that isn't a problem .

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Tamaized** [comment]
You can use a grindstone to remove enchantments.

**Comment by GizmoTheMoonPig** [comment]
(Please note that everything in this message is my thinking only, it doesn't reflect what the rest of the team thinks about this. I think its fun to chat about things like this but I don't want people thinking that I'm speaking for everyone who works on the mod here)
While this is a fun idea, I'm not particularly a fan of this at the moment. Set bonuses are not something I particularly see as vanilla, and we tend not to stray too far from the vanilla feeling when developing the mod. (Trust me, I've had many ideas rejected because of this). I also personally like the idea of armor mixing, so having set bonuses kinda kills that idea as it encourages you to get full sets of armor instead mixing and matching to get certain benefits from different pieces. 
Armor gimmicks can be cool if done correctly. The main gimmick with our armor is that most of it comes pre-enchanted. Ironwood, steeleaf, nagascale, and yeti all come pre-enchanted, and fiery technically comes pre-enchanted as it has built-in fire react. I think this is a nice simple way of doing things as you can easily make vanilla armor do the same if you please, and you can remove that gimmick from our armors with a datapack if you feel so inclined. Phantom armor not being lost on death is an interesting gimmick that I personally don't think makes a ton of sense, but as we tend not to change things like that I haven't said anything about it. That brings me into my next point: the gimmicks you mentioned don't make a ton of sense in regard to how the current armor sets act and what they're made of. 
- Ironwood and steeleaf being able to self-mend is not something I would ever expect them to do, considering the materials themselves are nothing more than just simple resources. the gear is meant to be disposable, much like how early game vanilla gear is. You're not gonna permanently keep a leather or iron armor set, you're gonna use it to help yourself out for a bit and get rid of it once you get something better. These armors should act that way as well imo, a sort of "in between" stage of you having absolutely nothing and getting the better gear the mod has to offer.
- Nagascale, if anything, should be more akin to how the naga itself is since its made directly from its skin. If I were to do anything with it I would make the armor give a small speed boost when sprinting as that would essentially act like the "charge" attack the naga does. The Naga isn't immune or hurt less by magic, so having that as its ability doesn't make much sense. (Pssst, since the naga chestplate is pre-enchanted with protection its already good against the lich! Protection absorbs some magic damage!)
- Arctic is supposed to be equivalent to leather essentially, considering it can be dyed and fur isn't really a special drop. You can get arctic fur before unlocking the snowy forest if you try hard enough, and its insanely easy to get a full set with the amount of yetis that spawn in the yeti caves. I think making it akin to diamond in terms of defense is way too OP. 
- Knightmetal having a high knockback resistance would make some sense to me. Perhaps something like having a high knockback res but it slows you down a bit would be a good tradeoff? I would imagine knightmetal to be a heavy armor set considering you're reforging it from scraps that enemies drop instead of directly forging it from ore. 
- Yeti protecting against fire damage makes very little sense to me. You're wearing a heavy jacket that protects you from the cold, if anything fire would hurt you more. Yeti armor already protects you from powder snow damage and the frosted status effect (arctic does the same!), I honestly think this set works as-is. 
Overall, some changes might be nice to have, but I don't think most of these really *work* with the mod at their current stage. Working with armor balancing is really tricky at times. The main goal of the mod in terms of difficulty is to be an alternate start to vanilla. The idea is you get your first diamond and make a portal. We want progression to scale similarly to how vanilla's "progression" scales, so we try to avoid anything too powerful. There's a few exceptions of course but those came before our time so there's not much we can do about them, as we don't like to make major changes to things unless everybody agrees on it.
Thanks for the suggestion though! You really got my gears turning when it comes to this, I'll probably be thinking about it for a bit now lmao

**Comment by DiamondWalker** [comment]
Hello. Thank you for taking the time to respond.
A few things I want to clarify:

-I wasn't talking specifically about full set bonuses. I actually don't like those a lot, since the force you to wait for a full set even if you manage to find one piece early.

-I used the naga leggings for the protection III. The chestplate has projectile protection, and I believe the death tomes count as magic attacks (correct me if I'm wrong).

-I thought the arctic armor was already around diamond tier? Might've made a mistake. The way it is now is fine; it's slightly better than iron.

-The idea for the yeti armor was that the fur would protect you from cold while some kind of ice magic would protect you from heat. Doesn't make a lot of sense, but it's what I could come up with.

You're right about the ironwood. I didn't think it through. Would be dumb to have unbreakable gear from a material you can easily get stacks of.

-----------------------------------------------------------------------------------------------------------------------------------

I get what you mean about trying to follow vanilla balance, but twilight forest doesn't feel like vanilla to me so far. In vanilla, there's a clear order of strength: you start with your wooden/stone tools. Then you get iron, then diamonds, and finally netherite. It makes sense.

In twilight forest, though, regardless of whether you make your portal or spawn in the dimension (like I did), you start with iron, then ironwood, then... diamonds? You can start mining them right away and skip everything, even if you restrict yourself to only using stuff from the dimension.

But I skipped diamonds (except for a helmet). I had everything (- helm) out of ironwood, which was slightly better than the iron I had before. So far so good.

Then I kill the naga. I make the leggings, which were a clear upgrade, but then there's the chestplate. iirc it had 0.5 armor toughness vs ironwood's protection I (the projectile protection on nagascale doesn't seem that useful). Already you have two pieces of armor, which, even though one is obtained later than the other, give almost identical protection.

Then I move on to the lich tower. There I find a few protection books, which I use to give my ironwood boots protection II.

After killing the lich, I'm at a loss on what to get next.

I replaced my ironwood chestplate with an arctic jacket, which seemed slightly better (and even then I'm not sure it's better). Neither knightmetal nor steeleaf seem to be a clear upgrade over the naga leggings, or the diamond helmet I made before I could even make ironwood, or the boots I made with only two enchanted books.

The only real way for me to actually progress now seems to be getting the yeti armor, which afaik is tied with fiery for best armor in the mod (despite being at different tiers, for some reason).

Hopefully that makes it clearer what my reason for suggesting this was.

**Comment by saltyseadoggo** [comment]
Sharing my two cents:
I do think diamonds should be banished from the TF, personally. Diamond gear outclasses all of TF's gear sets except for alpha yeti and fiery, and can be acquired before any of them by just mining in the TF. It could maybe stay in dark tower loot, as the tower is a later structure and you've already had the opportunities to use ironwood, naga, knightmetal and phantom armor/knightmetal and ironwood weapons/tools by then, but having it early on feels like it kinda defeats the point, you know?
Though I recognize that there's nothing stopping one from just going to the overworld to mine diamonds save for personal restraint

**Comment by Tamaized** [comment]
Then you wouldn't be able to make portals...

**Comment by GizmoTheMoonPig** [comment]
cant say I necessarily agree with diamonds being completely banished. TF doesnt really make them any easier to get as I guarantee 99% of people have never stepped foot in our caves before, and diamonds only generate in large hollow hills, arguably the most challenging structure in the mod. By the time you hit the dark tower you most likely have some other gear from the mod which balances things out imo.

> After killing the lich, I'm at a loss on what to get next.

See, this is where things get tricky. Because progression is no longer linear, the existing armor balance basically got thrown out the window. Yeti armor would've originally been one of the last armors you got as the alpha yeti came after the ur-ghast. Fiery would've come after steeleaf as steeleaf is found all over the labyrinth and armor pieces are included in the loot itself. Even looking at the armor spread from the old progression though I guess arctic was an oddball as you already got a full fiery set at that point (if you were lucky enough!) through the hydra and ur-ghast. 

I do think some sort of rebalance should be considered at some point. I don't even know if we adjusted to the 1.9 armor changes when the team took over since the mod was being ported from 1.7 to 1.10 at that point. 
Again, not promising anything, as I dont speak for the team here. I'll probably bring it up at some point though and see what others think.

**Comment by Andromander** [comment]
Might as well throw in my own thoughts, in no particular order.

- As mentioned, Grindstone removes the default enchants. Additionally, Uncrafting Table is more than just uncrafting and can be used to Recraft items, so instead of removing enchants, you could save the armour for use in recrafting, ie. transfer enchants across. But, I'll leave this as a minor point if the idea is to have default perks for each piece.
- Simplifying tiers...that's a nope. What's the point in getting the lower tiers if their armour and toughness sucks, regardless of what perk they introduce? There'd be no point in getting armour that has a super-cool perk when there's a better perk of "take less damage" above it, or several tiers above it in worst case.
- I'm putting a stop on any suggestion of self-repair because - even in vanilla - it's a lame concept that removes any agency in resource management - something that should be paramount in Minecraft. Even the Tinkers' Construct compat proved the Steeleaf trait was too OP in self-repair. Unless there's a rare or niche chance of it to regenerate and at a rate that only delays the armour breaking, it's not happening under my watch.
- A counterpoint to "vanilla doesn't have branching tiers" is Gold gear itself. Very low durability, but very high enchantability. Thing is, nobody uses Gold because of the issue with having a strict tier - why wear Gold for enchants when Diamond is objectively better at making you less likely to die?
- Ironwood and Steeleaf serves as opposites to each other: one has more durability, but the other has stronger enchants. If one were to suggest an idea, this concept should be considered in mind.
- I should note as well: while people assume that a Diamond is always acquired before entering the dimension, they also forget we have a config option to spawn directly in. There is no Iron, Diamond, or any resources brought in, you only have what the dimension can offer. Not to say these resources are unavailable, but the choice in using them becomes more about the player's own choices - it already was before, but required resources force the choice.
- The confusion in order is treating the armour as if there's a specific order to get them; reality is that TF armour doesn't quite work this way. Steeleaf is loot-based, so if you crawl dungeons and your armour gets wasted, you can craft and go, assuming you bring crafting tables with you. Ironwood, Knightmetal, and Arctic are forms of gathering and should each be better than just a patchwork in the event of armour failure - except maybe Arctic due to the ease of obtaining. Naga, Fiery, and Yeti are boss loot and should offer the better of perks, with Naga only slightly less so as it's the first boss. Should also note right now that Yeti shouldn't be better than Fiery as they are obtained from gold trophy bosses (Ur-Ghast, Hydra). The biggest key to making each piece of armour memorable is not "it made me survive until this point", but what it can do for you until it breaks.
- I know it's been drilled in already but like...you *do* realise Diamond is necessary for the portal? Not just that, but any crafting recipe that would feature it outside of equipment would become barred as a result. It's up to you if you crafted that Diamond gear and wore it because you saw it better than the other gear. Same with Netherite, however the difference for us is that not all 1.16 Nether features cannot fit into the dimension, and that's all Netherite is good for: equipment.
- Despite what people think about Netherite, it's only slightly better than Diamond in toughness and knockback. Only thing I would consider is giving one of the armour sets some knockback, and maybe some increased durability on the side for certain sets, but that's also a big if.

These would be my own considerations for improving gear:
- Knightmetal needs a little something than what it has right now. It is renewable, granted, but the processing and availability does negate this, and the perk should also be fairly minimal as a mid-grade armour. The weapons are combat heavy, so my only suggestion I can toss in is having some form of protection against specific forms of damage, perhaps higher mob attack resistance but a lack of protection against ranged forms of damage such as arrows or fire. Very dependent on availability to incentive, may be better off with something a bit more modest.
- Arctic is around Iron level in values and less durability, one for being renewable, the other...well it's just a winter jacket. It also boasts diamond-level toughness. I don't see too much reason to modify much around it except maybe some cold resistance in fighting the Yeti and Snow Queen.
- Naga is the first boss and only boasts two pieces of equipment, so having perks akin to Fiery and Yeti isn't quite necessary, but having a very small perk could be useful, perhaps encourage using it against the Lich as it is the next boss.

**Comment by Tamaized** [comment]
> Naga is the first boss and only boasts two pieces of equipment, so having perks akin to Fiery and Yeti isn't quite necessary, but having a very small perk could be useful, perhaps encourage using it against the Lich as it is the next boss.

It has protection.

**Comment by Killer-Demon** [comment]
Currently, as it stands, we are happy with how our armors are distributing their stats. We might revisit things in the future as they come up internally.
