### ISSUE TITLE
I can't kill Hydra with a gun and pierce Lich's shield with a gun.

### ISSUE THREAD

**Issue by mindy15963** [TeamTwilight/twilightforest#1879]
### Forge Version

1.20.1

### Twilight Forest Version

4.3.1846

### Steps to Reproduce

Please let me kill Hydra with a gun and let Lich's shield go through with a gun as well.

### What You Expected

I tried to kill Hydra using a gun in AVA mod(https://www.curseforge.com/minecraft/mc-mods/a-v-a-in-minecraft), but I failed, and I tried to kill Lich, too, but I failed because Lich's shield was immune to the gun.

### What Happened Instead

I tried to kill Hydra using a gun in AVA mod(https://www.curseforge.com/minecraft/mc-mods/a-v-a-in-minecraft), but I failed, and I tried to kill Lich, too, but I failed because Lich's shield was immune to the gun.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
The lich shield being immune is intentional. Lich shields only take damage from damage types tagged under `breaks_lich_shields`. This tag should really only contain damage types that are considered "magic", such as splash potions or twilight scepter bolts, but if mods want to add it to it so be it. You can also do this yourself with a datapack. 
The hydra is most likely intentional too. The hydra is immune to ranged attacks when the attacker is far enough away from it. Try standing closer when attacking with any ranged weapon.
