### ISSUE TITLE
[1.19.2] Cicada causing severe render lag.

### ISSUE THREAD

**Issue by Sandriell** [TeamTwilight/twilightforest#1914]
### Forge Version

43.2.21

### Twilight Forest Version

twilightforest-1.19.2-4.2.1518-universal

### Client Log

N/A

### Crash Report (if applicable)

N/A

### Steps to Reproduce

Simply walking through the Twilight Forest and within about 30 seconds the severe lag will set in.

### What You Expected

No lag

### What Happened Instead

Severe lag (1fps) when exploring the Twilight Forest.

### Additional Details

Spark Profile: https://spark.lucko.me/MQDPkoQj6Z

Mod List: https://gist.github.com/Sandriell/585349d10e92a848fed149a6798773e3

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
I can't reproduce this at all. I placed a 16x16x16 cube of cicadas (you will NEVER render this many cicadas while just casually playing, you may find like 10 at a time if you're lucky) and the lag wasn't nearly as bad as you said, with my profiler pointing to the rendering of the cicada model taking up the most resources. I didn't see ANYTHING show up regarding sounds, which is what your spark profile shows as taking up all the resources. 
I do think this is another mod's issue, considering you're running nearly 400 mods. Unfortunately, spark doesn't show mixins in their reports, so I have no way of telling which mod is causing issues, and I'm not about to go build this pack and test it myself as my free time is extremely limited. 
My best advice to you would be to try removing mods that you think may be causing issues (start with performance mods, they're always the ones that cause the most issues). If you do end up figuring out what the issue is let me know and I can look into fixing it for them.

**Comment by Sandriell** [comment]
After some investigating, I have determined the issue is with the mod Sound Physics Remastered https://legacy.curseforge.com/minecraft/mc-mods/sound-physics-remastered

Removing it completely fixes the Twilight Forest for me.
