### ISSUE TITLE
Hexxit Twilight Forest Crashing

### ISSUE THREAD

**Issue by ellinchworm** [TeamTwilight/twilightforest#1979]
### Forge Version

8.0.99.99

### Twilight Forest Version

3.11.1022

### Crash Report (if applicable)

https://mclo.gs/arBZQpw

### Steps to Reproduce

I was playing Hexxit and I was in the Twilight Forest and the game crashed. Every time I try to log on and play, it crashes again.

### What You Expected

I thought that if I restarted the game it would not crash.

### What Happened Instead

The game now crashes whenever I load into my world.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [x] I have confirmed this issue is unique and has not been reported already.

**Comment by Andromander** [comment]
I'm a bit confused on the mod version here because we don't have 3.11.1022, let alone a file that has "hexxit" in the name. This is potentially an issue with a third-party.

The only possible solution I can offer is to either reset the dimension or the chunk with the Final Castle in it. 1.12.2 hasn't been supported for a few years now.

**Comment by jodlodi** [comment]
Since Hexxit uses a custom version of TwilightForest, you will need to take this issue to the creators of the modpack.
There should be a link to their discord in the modpack's main menu
