### ISSUE TITLE
Please add the mod to Modrinth.

### ISSUE THREAD

**Issue by Alter73** [TeamTwilight/twilightforest#1994]
### The Suggestion

Hi! I just make quite a lot of modpacks (not just me) in the Modrinth launcher and a lot of mods have moved there. It is also possible because the service is developed only for Minecraft. It would be much more convenient if such a popular mod as Twilight Forest was also in Modrinth, otherwise I have to download it separately and check for updates, but this is very inconvenient when creating modpacks.

### Why Should It Be in the Mod?

Modrinth is a much more convenient and functional platform than CurseForge with its one of the best modding launchers, which many mods have switched to and such a legendary mod as Twilight Forest is very lacking there.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Tamaized** [comment]
They're a failed business.

**Comment by Alter73** [comment]
You're the first one to give me an answer. Thanks! However, I don't really understand why many developers switch to it in this case. It is extremely convenient, especially in categories, recommendations and absolutely no ads. And it is also open source. CurseForge loses in many ways with its buggy launcher and low functionality in terms of mods.

**Comment by ShiftySpace** [comment]
> They're a failed business.

I am curious for more info on this. I have not seen any discussion or evidence of them being a failed business so what makes you say that?

**Comment by Enderteck** [comment]
How is modrinth failing? It's getting more and more popular and it's even open source!

**Comment by Andromander** [comment]
What does being open source mean for a website?

**Comment by Enderteck** [comment]
It's not just a website, it's a modpack manager,a entire backend, a whole company giving their work for everyone.

**Comment by Alter73** [comment]
It's a pity that your team doesn't even think about the inconvenience it's causing its community because of your local drama. Twilight Forest is the same mod for Minecraft as many others, but for some reason everyone has already switched to Modrinth, which made life easier for their community, but it's a pity that you are not interested in it.

**Comment by GizmoTheMoonPig** [comment]
Trust me, it's not local drama. We're not the only ones that have issues with Modrinth. Don't make this about you.
Also everyone switching is not even remotely true, you wont find a TON of projects over on Modrinth that are on CF as guess what, other devs don't want to use the trashfire that's Modrinth either. 
This honestly isn't up for debate at this point, we may have considered it a few months ago but because of recent events that surfaced we definitely aren't even considering it anymore.

**Comment by Alter73** [comment]
Well, I probably don't understand what could "surface" new in the open source project. It's like a blank slate. It's just impossible to hide anything there. Perhaps this is one of the reasons for its popularity.

**Comment by GizmoTheMoonPig** [comment]
ok I don't think you understand what "open source" means. It simply just means the source code is open to the public. Twilight Forest is open source! Modrinth being open source is not the issue here. 
You're not taking into account everything else that's hidden from the public eye. The staff, the way they monetize projects, the way they handle projects. Things like this are things the average use won't see, but us mod devs are very aware of it. There's a lot of things there that we don't agree with in terms of how they're being handled. We don't want our project hosted on a company that's as much of a wreck as Modrinth is, that's all I'll say. I'm gonna be locking this as I'm getting really tired of responding to this.

Also I will say I personally don't care about what the community wants. I do modding for fun, not to please people. That argument will never work on me, I'm gonna do what I'm most comfortable with. This doesnt apply for everyone on the team but it does for me, so please stop saying I'm "inconveniencing the community". Most people still use CurseForge and the numbers show that, so I don't care about the small percentage of people who are so against using CF.
