### ISSUE TITLE
[Suggestion] Fabric 1.20.x?

### ISSUE THREAD

**Issue by allanonmage** [TeamTwilight/twilightforest#2005]
### The Suggestion

Did the Fabric port get abandoned?  The last update posted to Curseforge was about a year ago, while the forge version has had many updates since.

### Why Should It Be in the Mod?

Because you already started on it.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by GizmoTheMoonPig** [comment]
Just to clarify why this was closed, we dont currently have anyone working on the Fabric port of the mod. The port was handled by a small 3rd party team who have since dropped the project. Everybody on TeamTwilight uses forge (neoforge on 1.20.2+) and none of us have the time nor the drive to learn how fabric works
