### ISSUE TITLE
Hint Books are mostly empty

### ISSUE THREAD

**Issue by Divineaspect** [TeamTwilight/twilightforest#204]
Forge version: 8.0.99.99
Twilight Forest version: 2.4.0.106
Link to crash log: Not a crash.

Steps to reproduce:
1. collect and open a hint book

What I expected to happen: coherant text

What happened instead: about one word a page.

**Comment by williewillus** [comment]
Looks like the NBT tags on written books are now textcomponent JSON strings, previously in 1.7 they were just plain strings.

In fixing this we could also take the opportunity to move the actual text to lang files since if it uses textcomponents that means TextComponentTranslation is usable. The title/author still seem to be hard strings though.

**Comment by williewillus** [comment]
the format is documented here: https://minecraft.gamepedia.com/Commands#Raw_JSON_text
