### ISSUE TITLE
Ore hills not spawning

### ISSUE THREAD

**Issue by CreativeCubeMC** [TeamTwilight/twilightforest#2302]
### NeoForge Version

21.1.80

### Twilight Forest Version

4.6.2856

### Steps to Reproduce

1. Load the modpack
2. Go into Twilight Forest
3. No Ore hills generate properly

### What You Expected

Ore hills to have generated

### What Happened Instead

They did not.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Andromander** [comment]
From previous reports of this issue, this was likely a result of a mod conflict. Are there any mods present, and does this bug happen with only Twilight Forest?

**Comment by CreativeCubeMC** [comment]
Did they ever figure out what mod

**Comment by puzzlecube** [comment]
I have determined that the hills break if you have the YUNG's API mod installed even without any of the better structure mods that go along with it.
I tested it with both 5.1.1 and 5.1.3 of the API on the same Minecraft and Neoforge versions and both versions broke hollow hills making them only generate as a spot with a lot more ores in the ground and a few columns of stone poking through the grass blocks. This also breaks the Hydra's lair and instead of the usual spiky overhang of ores it will generate a completely flat disk of stone.
The places where all of these POIs would generate do get detected by /locate and /twilightforest map_locator commands as expected though too in the exact same location as without YUNG's API.

**Comment by Drullkus** [comment]
Fixed via [82f1b4b](https://github.com/TeamTwilight/twilightforest/commit/82f1b4b9c15eedcc4fbaccdd513d0b44d818710c)

**Comment by CreativeCubeMC** [comment]
When can see possibly see this fix in the mod?

**Comment by Drullkus** [comment]
The fix will be in the next release, do you prefer this ticket to be closed when the fix is released? Love to give an ETA but we don't do those

**Comment by CreativeCubeMC** [comment]
Yes, please!

**Comment by Drullkus** [comment]
Fixed in [4.6.2941](https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest/files/5983260)
