### ISSUE TITLE
[1.12.2] Crash TPing to a Custom Dimension - Simple Dimensions Compat?

### ISSUE THREAD

**Issue by MokahTGS** [TeamTwilight/twilightforest#334]
Forge version: 2540
Twilight Forest version: Twilight Forest - MC 1.12.2 - 3.3.202
Simple Dimensions Version: 1.12.1.3.1
Link to crash log: https://pastebin.com/yfe6Pedj

Steps to reproduce:
1. Create a New Dimension with SD.
2. Use the SD commands to TP to the new dimension.
3. Crash

What I expected to happen:

What happened instead:

**Comment by Andromander** [comment]
The crash log seems to be pointing to an Advancement-related area, more specifically, HasAdvancement

**Comment by MokahTGS** [comment]
Yes and it also corrupts the save game when this happens.

**Comment by Tamaized** [comment]
This happens because Simple Dimensions has a WorldCustom that overrides WorldServer#init without calling super and thus `advancementManager` is now null.
https://github.com/lumien231/Simple-Dimensions/blob/master/src/main/java/lumien/simpledimensions/server/WorldCustom.java#L65-L85

issue is on their end, @lumien231
