### ISSUE TITLE
Aurora block problem

### ISSUE THREAD

**Issue by Caopr** [TeamTwilight/twilightforest#336]
Forge version: 14.23.0.2531
Twilight Forest version: 3.3.202

Going anywhere near the aurora palace causes everything to lag like crazy unless the game is paused. I noticed its due to the blocks changing color. perhaps just add a config option to turn the visual effects off?

**Comment by williewillus** [comment]
is it client or server lag? The color changing should not contribute to lag any more than say a bunch of water, it's just an animated texture.

**Comment by Caopr** [comment]
Running singleplayer. anytime Id go near the palace unless the game was paused chunks wouldent even load.I assumed it would somehow be the textures due to them stopping when paused

**Comment by Andromander** [comment]
I'd say that would be worldgen lag. I also don't think the Aurora Palace had been touched since the dev builds, and it may be unoptimised.

**Comment by Killer-Demon** [comment]
It is incredibly unlikely that Aurora Blocks can cause this as they function the same way water has with a animated texture.

Feel free to reopen this issue if this issue still persists in the latest version, a debug profile is needed to find the cause then.

**Comment by Tamaized** [comment]
Linking this to https://github.com/TeamTwilight/twilightforest/issues/733#issuecomment-508971304as i'm sure this is the real cause and to finally solve the mystery of this issue.

**Comment by leilsonnatan** [comment]
I have the same problem but even pressing esc not for I noticed that the animation itself that for some reason I get lag at 1 fps and I go back to normal maybe it’s errors being generated by something, I didn’t go to another castle to test if it changes but I think it is the block, I was flying seeing each direction of the block whenever I looked at it lagava or when I am not really loaded chunk. If anyone knows how to solve it please help I wanted to play every twilight like the giants but I can't because of that
