### ISSUE TITLE
Charms and Soulbound enchantments

### ISSUE THREAD

**Issue by Caopr** [TeamTwilight/twilightforest#338]
Forge version: 14.23.0.2531
Twilight Forest version: 3.3.202

So when using both a charm of keeping and a charm of life at once it would cause soulbound items to be destroyed.

said soulbound effects came from 2 mods. Corpse Complex. and a soulbound tinkers tool from using a nether star.

only soulbound items are destroyed from my notice. Did not seem to destroy the items if only a charm of life was used.

**Comment by Andromander** [comment]
The Charm of Keeping and Charm of Life should not be working at the same time. The only item that may be destroying soulbound items is Charm of Keeping. Charm of Life only restores health once the player is meant to die.

I'm not sure how soulbound items work, so I'm not sure if there's something else in there that I'm missing

**Comment by Caopr** [comment]
Oh. well when I die with both charms in my inventory the sprites for both charms fly around my character. same time.

**Comment by Caopr** [comment]
Soulbound items work a bit like the charm of keeping. but as an enchantment

**Comment by TheIllusiveC4** [comment]
Forge version: 14.23.0.2542
Twilight Forest version: 3.3.202

I'm the author for Corpse Complex, the mod where this issue was initially opened. In my investigation of this issue, I personally found that Soulbound items were irrelevant. I tested an instance with only Forge and Twilight Forest installed and found that, upon death, both Charm of Keeping and Charm of Life will activate and the items that should have been kept by the Charm of Keeping are destroyed. I suspect that since Charm of Life activates, the items that Charm of Keeping were storing are lost.
