### ISSUE TITLE
World Type: Twilight Forest

### ISSUE THREAD

**Issue by Divineaspect** [TeamTwilight/twilightforest#345]
This is a feature request, 
I would like the ability to set Twilight Forest as the overworld type, which should also allow me to select those world types for Advanced Rocketry.

Thank you for your time, effort, and consideration of my request.

**Comment by Tamaized** [comment]
Would just require us to call `new WorldType(...)` somewhere while overriding `getChunkGenerator`, it registers itself.

**Comment by williewillus** [comment]
I poked this briefly, it's not as easy as it seemed to be on first glance

You subclass WorldType where you can give the BiomeProvider and ChunkGenerator, but since it's Dimension 0 a `WorldProviderSurface` is used and ours isn't, period. There's no good point to interpose on this, since the mapping of dim id -> type of world provider is held as ground truth in forge.

In addition would also have to disable portals and stuff like that

**Comment by Tamaized** [comment]
Closing as WorldTypes are in all honestly entirely pointless, and don't even work in 1.16+ for datapack dimensions.
If you really want this kind of feature, just set players to spawn in TF via config or you can datapack the overworld to match TF generation
