### ISSUE TITLE
Entering the Twilight Forest causes an instant 'lost connection: timed out'

### ISSUE THREAD

**Issue by belathus** [TeamTwilight/twilightforest#349]
Forge version: 14.23.0.2549
Twilight Forest version: 3.4.239
Link to crash log: Not a crash
Server-side log when player enters the Twilight Forest:
```[12:17:55] [Server thread/INFO] [journeymap]: TBone311_xXx joining dimension 7
[12:18:23] [Server thread/INFO]: TBone311_xXx got revenge on Wither Cat
[12:27:15] [Server thread/INFO] [journeymap]: TBone311_xXx joining dimension 0
[12:27:15] [Server thread/INFO]: TBone311_xXx lost connection: Timed out
[12:27:15] [Server thread/INFO]: TBone311_xXx left the game
[12:27:15] [Server thread/WARN]: handleDisconnection() called twice```
```

When the player tries to rejoin the server, they frequently get kicked:
```[12:27:51] [Server thread/INFO] [FML]: [Server thread] Server side modded connection established
[12:27:52] [Server thread/INFO]: TBone311_xXx[/75.180.33.43:61358] logged in with entity id 223336 at (95.52201569967558, 33.0, 312.7416248576079)
[12:27:52] [Server thread/INFO]: TBone311_xXx joined the game
[12:27:52] [Server thread/INFO] [journeymap]: TBone311_xXx joining dimension 0
[12:27:52] [Server thread/INFO] [extraalchemy]: Asking client for config status
[12:27:52] [Server thread/INFO] [journeymap]: Sending log in packet.
[12:27:52] [Server thread/INFO] [Astral Sorcery]: [AstralSorcery] Synchronizing configuration to TBone311_xXx
[12:27:59] [Server thread/INFO]: TBone311_xXx lost connection: Timed out
[12:27:59] [Server thread/INFO]: TBone311_xXx left the game
[12:28:18] [Server thread/INFO] [FML]: Unloading dimension 7
```
And, going back to the Twilight Forest:
```[12:30:02] [Server thread/INFO] [journeymap]: TBone311_xXx joining dimension 7
[12:30:02] [Server thread/INFO]: TBone311_xXx lost connection: Timed out
[12:30:02] [Server thread/INFO]: TBone311_xXx left the game
[12:30:02] [Server thread/WARN]: handleDisconnection() called twice
```

Steps to reproduce:
1. Make a server
2. Make a portal, then enter Twilight Forest on the server

What I expected to happen:
Enter the twilight forest after the loading screen

What happened instead:
The moment the loading screen shows, the server "times out." This takes less than a second, as you can see from the time stamps.

**Comment by Andromander** [comment]
Can you try replicating this issue with only Twilight Forest? I can see other mods in the logs, and removing them may narrow down the issue

**Comment by Tamaized** [comment]
client logs when this happens would be ideal

**Comment by DarkWav** [comment]
Im having the exact same problem with no other mods installed...
This bug does not happen in singleplayer at all, it is a server side only bug.

**Comment by belathus** [comment]
I'll grab a client-side log when I get home tomorrow. Holidays and all that.

**Comment by jhoov** [comment]
I also have this problem, but not with one player.  It happens when more than one player tries to connect.
[latest.log](https://github.com/TeamTwilight/twilightforest/files/1503208/latest.log)

**Comment by Morpheus1101** [comment]
I've not tested with TF standalone, but with my current pack im developing 9/10 when going to TF you get disconnected

**Comment by katubug** [comment]
Is this fixed? I'm having an issue where myself and my players get kicked from the server while traveling to OR from TF. Most of the time it says "connection lost" but other times it gives a java exception.

**Comment by Morpheus1101** [comment]
This is fixed for me travelling from OW an TF an reverse consistently

**Comment by katubug** [comment]
Did you do something to fix it? Or it just stopped happening? Mine was still present as of last night, although after about 10 login attempts, I managed to get back onto the server.

**Comment by Andromander** [comment]
Can you post a client log for this? It may help to diagnose the problem

**Comment by katubug** [comment]
I'm sorry, I don't know which is the important file. Here's all the recent logs:

[fml-client-2.log](https://github.com/TeamTwilight/twilightforest/files/1545278/fml-client-2.log)
[fml-client-3.log](https://github.com/TeamTwilight/twilightforest/files/1545279/fml-client-3.log)
[fml-client-latest.log](https://github.com/TeamTwilight/twilightforest/files/1545280/fml-client-latest.log)
[latest.log](https://github.com/TeamTwilight/twilightforest/files/1545281/latest.log)
[fml-client-1.log](https://github.com/TeamTwilight/twilightforest/files/1545282/fml-client-1.log)

I click to join the server, it brings up the "Whisking you away from the Twilight Forest" screen, and then it disconnects me. All my current logs are me attempting to travel via Bonfire (from the mod Bonfires), but I recall it happening with the normal portal as well. Let me know if you want me to test the regular portal.

As an addendum, the java server exception error also sometimes just happens when joining the server. So I'm not sure if that portion is related to TF.

**Comment by Andromander** [comment]
Your version of Twilight Forest is outdated. Update to 3.5.263, since this should fix the timeout issue.
