### ISSUE TITLE
Miner's Tree loves iron too much

### ISSUE THREAD

**Issue by EpicKillKitty** [TeamTwilight/twilightforest#392]
Forge version: 14.23.0.2550
Twilight Forest version: 3.5.263
Link to crash log: No crash log

Steps to reproduce:
1. Plant a miner's tree

What I expected to happen:It pulls up various ores for me to happily mine.

What happened instead: Over a 2 week period, my miner's tree pulled up nothing but iron. 14 full stacks of iron. I tried going to a different area and trying it there (even went into creative and made a little cave of random ores under the tree) nada, just iron. I am playing on a server not in single player (i know sometimes that causes issues) and yeah.

**Comment by Drullkus** [comment]
What's the modpack or what mods do you have?

**Comment by EpicKillKitty** [comment]
It's called Kitty-n-Couch's New Adventure. (located here https://www.technicpack.net/modpack/kitty-n-couchs-new-adventure.1118290)

The mods are:
Twilight Forest; Tinker's Construct; Gravestone mod; Inventory Tweaks; Just Enough Items; Mantle; MC Multipart; Pam's Harvestcraft; Roguelike Dungeons; Mr. Crayfish's Furniture Mod; ToroHealth Damage Indicators; Treecapitator; Xaero's Minimap; Chisel's and Bits; Bibliocraft; Better FPS; Biomes O' Plenty; Backpacks; AtomicStriker's Battle Towers; ConnectedTexturesMod; Tinker's Tool Leveling and Iron Chests

**Comment by EpicKillKitty** [comment]
I was wondering if any headway had been made on this.

**Comment by Drullkus** [comment]
Basically the tree picks the ores from the ground by random. It doesn't "make" the ores. It will pull them from randomly anywhere within a 32x32x32 cube radius. By placing them on the surface it makes sense that you're having a bad time seeing other ores as iron is pretty much common on the upper ground levels. If you placed them around Y20 you'd see much better results. Otherwise there is zero code in the algorithm that makes it biased towards iron.
