### ISSUE TITLE
Silk Touch & General Harvestability Problems

### ISSUE THREAD

**Issue by Killer-Demon** [TeamTwilight/twilightforest#446]
Using Silk Touch on:
 - Canopy Tree Wood
 - Mangrove Wood
 - Darkwood Wood
Returns Twilight Oak Wood.

Using Silk Touch on:
 - Transwood
 - Minewood
 - Sortingwood
Returns Timewood.

Using Silk Touch on a tool other than Shears on:
 - Twilight Oak Leaves
 - Canopy Tree Leaves
 - Mangrove Leaves
 - Rainbow Oak Leaves
Returns tile.TFLeaves.[number].name
`[number]` being different depending on which leaves.

Using Silk Touch on:
 - Nagastone Head
 - Nagastone
Returns tile.TFNagastone.[number].name
`[number]` being different depending on which block.

Using Silk Touch on a tool other than Shears on:
 - Timewood Leaves
 - Leaves of Transformation
 - Miner's Leaves
 - Sorting Leaves
Returns tile.TFMagicLeaves.[number].name
`[number]` being different depending on which leaves.

Using Silk Touch on:
 - Stronghold Shield
Gives the block without texture.

Using Silk Touch on:
 - Trophy Pedestal
Returns tile.TFTrophyPedestal.1.name

Using Silk Touch on a tool other than Shears on:
 - Thorn Leaves
 - Beanstalk Leaves
Returns tile.TFLeaves2.[number].name
`[number]` being different depending on which leaves.

Harvesting:
 - Violet Castle Door
 - Pink Castle Door
 - Blue Castle Door
Returns Yellow Castle Door.
See issue: #415

Encased Smoker/Fire Jet are treated as stone harvestability (should be wood) and have the breaking particles of Stone.

Block of Arctic Fur doesn't break faster with Shears.

**Comment by Andromander** [comment]
Forge Version: 23.14.2.2641
Twilight Forest Version: 3.6.372

Tested this again in the latest build. There are still a few issues (some that I am uncertain about, but I will report them anyway)

Using Silk Touch on a tool other than Shears on:

* Twilight Oak Leaves
* Canopy Tree Leaves
* Mangrove Leaves
* Rainbow Oak Leaves
Returns nothing

Using Silk Touch on:

* Nagastone Head
* Nagastone
Returns nothing

Using Silk Touch on a tool other than Shears on:

* Timewood Leaves
* Leaves of Transformation
* Miner's Leaves
* Sorting Leaves
Returns nothing. I assume this is intentional?

Using Silk Touch on:

* Stronghold Shield
Returns nothing. I assume this is intentional?

Using Silk Touch on:

* Trophy Pedestal
Returns nothing. Can be harvested without Silk Touch

Using Silk Touch on a tool other than Shears on:

* Thorn Leaves
* Beanstalk Leaves
Returns nothing

Encased Smoker/Fire Jet are treated as stone harvestability (should be wood) and have the breaking particles of Stone.

Block of Arctic Fur doesn't break faster with Shears.

BONUS ROUND: Breaking Beanstalk Leaves may return Magic Beans, but untextured.

**Comment by Tamaized** [comment]
Everything here seems to have been solved by now save the fire jets and arctic fur but I just fixed these in 92336f4f4c8ea911177d542a23a2cf191f596450 and cbcbe7f7b1c1d1ccd977496a998ef55fcf12d9bf respectively.

**Comment by bs2609** [comment]
For posterity, will add castle pillar blocks - fixed by 6c1439763e1d6e55be65a4ded8bf95226ce3447c.
