### ISSUE TITLE
Twilight Portal can be smaller than 4 blocks

### ISSUE THREAD

**Issue by Andromander** [TeamTwilight/twilightforest#485]
Forge version: 14.23.3.2673
Twilight Forest version: 3.7.398

The portal can be built up to 64 blocks, but should be restricted to not be smaller than 4 blocks. This is not the case, and 1 block portals can be made.
![2018-04-29_10 14 21](https://user-images.githubusercontent.com/29526717/39412008-7112d3ce-4c58-11e8-902e-f5dccbf77cb1.png)

**Comment by bs2609** [comment]
See:
https://github.com/TeamTwilight/twilightforest/blob/11db4d19d86e29f8bf966c1c620db335825af256/src/main/java/twilightforest/block/BlockTFPortal.java#L95-L116

The check is for `number.getInt() > 3`, but number is initialised to 64 and decremented, instead of being initialised to 0 and incremented.
