### ISSUE TITLE
[1.13] Split major structures into different structures

### ISSUE THREAD

**Issue by williewillus** [TeamTwilight/twilightforest#492]
currently literally everything is dumped into the single type TFFeature.

benefits of splitting it:
* advancements can query which one you're in (minecraft:location trigger)
* /locate can find specific structure types
* exploration maps can point to specific types
* cleaner code

**Comment by Drullkus** [comment]
I’m 500% on board for this.

**Comment by Drullkus** [comment]
So since I hear 1.13 is going still be a ways off, and Forge 1.13 even further off, I may just handle this now.

A Datafixer can be applied to move id key `FeatureID` to the actual structure ID key `id`, making this practically trivial to handle in the immediate future instead.

**Comment by Drullkus** [comment]
Partially handled via 4c9ffe5b8dab6ab452aab3f6e647ec28ee62e276

**Comment by Drullkus** [comment]
Soooo... Turns out I'd not only have to apply a datafixer, but I'd need to move them into their own NBT files 🤦‍♂️ 

![](https://cdn.discordapp.com/attachments/343501360517611531/456106944533495808/unknown.png)

![](https://cdn.discordapp.com/attachments/343501360517611531/456108226069397504/unknown.png)

**Comment by Tamaized** [comment]
This was completed when 1.14 rolled around
