### ISSUE TITLE
Ur-ghast falling tears not visible in multiplayer

### ISSUE THREAD

**Issue by Benimatic** [TeamTwilight/twilightforest#497]
Steps to reproduce:
1.  Fight ur-ghast until it begins its tantrum

What I expected to happen:

Giant ghast tears fall and shatter under the boss

What happened instead:

No visible tears, player takes damage from no apparent source

**Comment by bs2609** [comment]
Done via proxy, so only works on singleplayer client atm:
https://github.com/TeamTwilight/twilightforest/blob/cbfd798122b3ddb5b262ed613d2eb17caafa3334/src/main/java/twilightforest/entity/boss/EntityTFUrGhast.java#L344

The particle spawning here could be moved to the Ur-Ghast's `onLivingUpdate`, the AI code only runs on the logical server.

**Comment by bs2609** [comment]
It might also be better to check `getPrecipitationHeight` here instead of `canSeeSky`:
https://github.com/TeamTwilight/twilightforest/blob/e9752dc08877447fb5ca53b85e84f70236ec89b5/src/main/java/twilightforest/entity/boss/EntityTFUrGhast.java#L364

(`canSeeSky` uses the heightmap based on block opacity, whereas `getPrecipitationHeight` checks the block material, matching rainfall probably makes more sense here)

**Comment by Drullkus** [comment]
I'm unsure how to handle that check for the `getPrecipitationHeight`, could you clarify that, please?
