### ISSUE TITLE
Some items registered with Thaumcraft Aspects are missing their Aspects

### ISSUE THREAD

**Issue by Andromander** [TeamTwilight/twilightforest#498]
Forge version: 14.23.3.2678
Twilight Forest version: 3.7.415

The items `Raven's Feather`, `Torchberries` and `Giant Log` have been assigned Aspects according to the compat class. However, the version used to check the aspects in-game seemingly don't have their Aspects. They are also unusable in a Crucible, meaning this may not be a visual issue.

**Comment by Drullkus** [comment]
What version of Thaumcraft? Azanor said something about Aspects in the Beta13.

**Comment by Andromander** [comment]
Yea, using Beta 13. Tested it in Beta 11 by accident and thought that was the issue, but after an update, they still had no Aspects.

**Comment by Andromander** [comment]
Tested with TF 3.8.551, Forge 14.23.4.2705 and Thaumcraft Beta 16. Those items now have their Aspects showing now. I guess this is resolved.

**Comment by bs2609** [comment]
Seems that Thaumcraft calculating aspects for items based on crafting recipes is causing this issue - if it encounters these items before we've registered aspects for them, it'll mark them as having no aspects.
If this is done with a specific meta value from the recipe, then our later wildcard registration won't work because an exact metadata match will take priority.

**Comment by bs2609** [comment]
Hopefully 634a84e34652feed3ee964cbb3270e988aa01a47 should resolve this for those specific broken items, let us know if you find anything else with issues.

**Comment by Andromander** [comment]
Yup, that appears to be working again.
