### ISSUE TITLE
Chunkerrors while dying

### ISSUE THREAD

**Issue by coon58** [TeamTwilight/twilightforest#573]
Forge version: 14.23.4.2729
Twilight Forest version: 1.12.2-3.7.424

Hi, i found a bug.
Everytime I die in the Twilight forest i get teleported out of it in the Overworld, but there are still some chunks from the Twilight forest loaded in the Overworld for some reason, which causes me to get stuck in mid air. The only way i can "fix" it is reloading the world.
Btw, i play with the worldgen "amplyfied".

**Comment by Tamaized** [comment]
Uh, i've NEVER experienced nor heard of this before. Perhaps a mod conflict of some sort?

**Comment by Andromander** [comment]
Mod conflict would probably be a reasonable conclusion, though there's not really much information to go off from this. It sounds like there's some sort of processing issue because there's mention of "getting stuck in mid air". Could just be chunks trying to load in.
If more information can be provided, feel free to reopen this issue.
