### ISSUE TITLE
Giant's Pickaxe issue

### ISSUE THREAD

**Issue by zuzzlan** [TeamTwilight/twilightforest#593]
Forge version: 14.23.4.2738
Twilight Forest version: 3.7.424 (recent one for 1.12.2)
Link to crash log: -

Steps to reproduce:
1. Enchant Giant's Pickaxe with efficiency
2. Mine a giant block
3. Observe

What I expected to happen: To mine the giant blocks faster than without an efficiency 5 enchant

What happened instead: It has the same mining speed as without efficiency 5 on giant blocks

**Comment by bs2609** [comment]
As far as I can tell, the giant pick is correctly affected by efficiency here - it's just that due to the way the enchant works, you aren't likely to notice the difference on giant blocks.

This is because efficiency adds a speed bonus, rather than applying a multiplier. As the giant pick already gets a 64x multiplier to it's effectiveness against giant blocks, the efficiency bonus is relatively small: with eff. V, for a normal block, you go 4 -> 30 (x7.5), but for a giant block, it's 256 -> 282 (x~1.1).

As the giant pick already has an extra bonus against giant obsidian, this hopefully shouldn't be too much of a letdown in practice.
