### ISSUE TITLE
[Issue] Aurora block being registered as Packed Ice

### ISSUE THREAD

**Issue by TomaszewskiPatryk** [TeamTwilight/twilightforest#607]
**Forge version:** 14.23.4.2708
**Twilight Forest version:** 3.8.654

**Steps to reproduce:**
1. [Click here](https://github.com/TeamTwilight/twilightforest/blob/7b86ed7774d16d13887947b1ef768950dd42df9f/src/main/java/twilightforest/block/BlockTFAuroraBrick.java#L27)

**What I expected to happen:**
Since aurora block doesn't have any slipperiness, it shouldn't be registered as "Packed Ice".
(It applies to both **Aurora Block** and **Aurora Pillar**).

**What happened instead:**
It is registered as "Packed Ice", causing incompatibility with other mods (for example [Chisels and Bits](https://minecraft.curseforge.com/projects/chisels-bits?gameCategorySlug=mc-mods&projectID=231095)).

**Comment by Tamaized** [comment]
Not quite sure if I understand how setting the material would cause issues.

**Comment by TomaszewskiPatryk** [comment]
Other mods may assume that, since it's "Packed Ice", it has all of its properties, including slipperiness.
And that's exactly what happens with [Chisels and Bits](https://minecraft.curseforge.com/projects/chisels-bits?gameCategorySlug=mc-mods&projectID=231095) ([Issue #424](https://github.com/AlgorithmX2/Chisels-and-Bits/issues/424)), chiseled aurora blocks gain slipperiness, even though they shouldn't.

**Comment by bs2609** [comment]
Materials don't have a slipperiness value though, that's entirely defined by the block.

**Comment by Tamaized** [comment]
No other material really fits for the aurora block anyhow imo.

**Comment by TomaszewskiPatryk** [comment]
Yeah, I guess you are right, I didn't think about that...
But there is still incompatibility between two mods, and both authors say the fault is on the other side :/

**Comment by AlgorithmX2** [comment]
I'm not saying that the fault is Twilight Forest for the issue, I simply asked if there was a reason they choose to use that material, instead of something else. Since the material is the reason C&B opted to treat it the way it did.

If there was no reason, it would be something easily changed, and nothing would really need to in either mod significant amount.

If there was in-fact a reason for such a thing, I would need to rethink how I deal with that and completely implement a new emulation process for it, decreasing performance / increasing memory requirements to some amount. For what I generally consider pretty low tier feature, something I don't really think is worth the CPU cycles and bytes required to emulate it fully. This is my own opinion at least.

I only brought it up, since it being ice just seemed strange to me, and it seems I'm not the only one to think so.
