### ISSUE TITLE
Compatibility between transformation powder and Animania

### ISSUE THREAD

**Issue by Alessandro404** [TeamTwilight/twilightforest#610]
Right now the transformation powder doesn't works when Animania is installed. Most of the time boars, deers and penguins simply vanish, without generating a overworld version.

Only sometime, a female of one species (always the same) is generated, but I suspects its not a intended behaviour.

The Ideal solution would be that every time a twilight forest mob is transformed, the corresponding creature from animania is created checking maybe the preferred biome (animania has species that have preferred biomes) and with a random sex.

**Comment by bs2609** [comment]
How does the behaviour look with build 669+ (can get it [here](http://builds.steamnsteel.info/browse/TF-ONETWELVE))?

**Comment by Alessandro404** [comment]
After some testing, it seems that almost nothing changed. 
The only difference, is that once I've found a different species of pig. I'm not user if that is because of the newer build tho. It may be just luck

**Comment by GizmoTheMoonPig** [comment]
I'm not sure if this is still a relevant issue, but just in case, transformation powder transformations are now handled through json "recipes" so to say. (See #1360 for more info) Since it looks like animania is still stuck in 1.12, we can't exactly provide support for it right now. If it updates, and making new json recipes doesn't fix the issue, please reopen this and we can troubleshoot it.
