### ISSUE TITLE
twlight forest crash

### ISSUE THREAD

**Issue by CraftyCutie** [TeamTwilight/twilightforest#612]
Forge version: 1.12.2-14.23.4.2759
Twilight Forest version: (this is the build number) 3.8.654
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline) https://gist.github.com/CraftyCutie/4e9591ce8f3bcf5f1e4a23916326b1a4
I hope I did this right...

Steps to reproduce:
1. open minecraft
2. press play

What I expected to happen: the game to work

What happened instead: crash

**Comment by Andromander** [comment]
Update Thaumcraft

**Comment by bs2609** [comment]
Duplicate of #606.

Currently we require a minimum version of `6.1.BETA21` for Thaumcraft, ~~unfortunately it seems the game crashes before the dependency check happens~~.
**Update:** turns out the dependency on Thaumcraft wasn't written out correctly, so the checking didn't work. It's been fixed for future versions (by 76b7f46283b0af87ba69ebcbebc4581139c796f1).

**Comment by CraftyCutie** [comment]
sorry for the duplicate... but ty!
