### ISSUE TITLE
Portal Overworld Spawn

### ISSUE THREAD

**Issue by Darkosto** [TeamTwilight/twilightforest#617]
Forge version: 2760
Twilight Forest version: 3.8.654

Steps to reproduce:
1. Create TF portal in OW
2. Go to TF
3. Come back and you will be in a new portal location despite having a valid original portal

What I expected to happen: To use my original portal (to note, this is a much worse issue because of Skylight Forest since you are in the void far from your base)

Thank you! Take care!
DarkSolo

**Comment by bs2609** [comment]
If it's available the `debug.log` file from when you were teleporting would be helpful - in particular, I'd like to know if any of these messages show up:
https://github.com/TeamTwilight/twilightforest/blob/5508fdd957a34ab450a21eef871fff87a98638eb/src/main/java/twilightforest/TFTeleporter.java#L57-L77

In addition, doing the following would also be useful:

1. Go into creative and hover above your original overworld portal.
2. Run the command `/forge setdim @p 7` (or whatever the TF dimension ID is here)
3. Give yourself a blank magic map and open it.

What does that area look like on the map? (where a non-relocated portal would end up)

**Comment by ranger135xp** [comment]
For me, Forge 2772
TF: 3.8.689

Issue happens to me as well.
Followed suggested command and got here:
![image](https://user-images.githubusercontent.com/15115164/48981197-78fbc680-f0a0-11e8-877d-7dd1fec8f03a.png)

**Comment by bs2609** [comment]
Generally, this is due to the "entry" portal pointing to an area which is unsafe, as can be seen on the magic map following a direct teleport with commands.

If the first safe point that can be found is too far away from the original entry point, the portal will be unable to link back.

For the case of void worlds where the original portal may not be easily accessible e4e8d51f4542add14fd2778852d260da3042e4cb adds a config option `checkPortalDestination` which will cause portals to fail to form if the original destination is unsafe. This requires searching for a "safe" portal spot manually, but should ensure a successful return trip.

**Comment by ranger135xp** [comment]
I wonder if this is an incompatibility or an issue caused by the mod NetherPortalFix as it appears to change something with portals.

**Comment by Darkosto** [comment]
I do not use NetherPortalFix and still have the issue occur in my packs.

**Comment by ranger135xp** [comment]
My mistake, I thought that mod was in SevTech.
I'm using a modified FTB Revelation pack, which I think included NPF.

I now have Forge 14.23.5.2807 and TF 3.8.689

**Comment by drewkeating** [comment]
This exact issue is happening with the "Dungeons, Dragons and Space Shuttles" mod pack, version 7.4a, which uses twilightforest-1.12.2-3.10.1013-universal

**Comment by GizmoTheMoonPig** [comment]
redirecting this to #1459 so we can keep track of every portal issue in 1 place
