### ISSUE TITLE
Biome Weather Effects persist with tfEnforcedProgression set to False

### ISSUE THREAD

**Issue by Andromander** [TeamTwilight/twilightforest#627]
Forge version: 14.23.4.2759
Twilight Forest version: 3.8.716

Steps to reproduce:
1. Set `tfEnforcedProgression` to `false`
2. Run around the biomes that are affected by Progression, making sure they are locked

What I expected to happen:
Weather effects shouldn't render.

What happened instead:
It seems that the weather effects continue to play out, despite having set `tfEnforcedProgression` to `false`. The structure protection still plays out normally (as tested with a Lich Tower before having slain a Naga). The weather effects do not induce their effects when walked in to, so it appears to just be a visual discrepancy.

**Comment by bs2609** [comment]
As far as I can tell, this happens if you change the game rule while in the dimension - as the change won't immediately be synced to the client, you'll still see the visual effects.

Unfortunately, as the game rule is set by a vanilla command, we aren't notified of the change. We could poll it every tick to check for changes, but I'm hoping https://github.com/MinecraftForge/MinecraftForge/pull/5152 will provide for a better solution.

**Comment by Andromander** [comment]
Ah yes, I forgot to state that.
I had changed the gamerule within the dimension, no restarting of the world/game, or changing dimension.

**Comment by bs2609** [comment]
Looking into this further, we do attempt to intercept the `/gamerule` command being sent to handle notifying clients - perhaps this isn't working properly?

**Comment by bs2609** [comment]
Hopefully c587036df7b683be44103e812dc38feefb1ccc64 will make this work more reliably.
