### ISSUE TITLE
Liches spawning in overworld (likely another mod conflict)

### ISSUE THREAD

**Issue by ghost** [TeamTwilight/twilightforest#668]
Preface: I'm not blaming any one mod as I'm not sure what's triggering the issue, I am instead seeking a direction.

Forge version: 2768
Twilight Forest version: 1.12.2-3.8.689
Link to crash log: N/A

I'm not sure where to go with this from here, I figured maybe someone here could shed some insight into this issue. Long story short, I use OTG+BiomeBundle, and for some reason twilight lich's are spawning in certain overworld biomes. I made a post on the BiomeBundle github, but no response as of yet (a month later).

https://github.com/BiomeBundle/BiomeBundle/issues/151

**Comment by ghost** [comment]
Found the issue: https://github.com/Tamaized/Dal-Quor/issues/239

**Comment by Gunner76th** [comment]
@DemonfangArun The github issue you posted is no longer on github as the repo has since been removed. Do you remember how that mod was causing the Lich to spawn in the overworld? Also was it only the lich or were other bosses such as the Naga spawning as well? In Roguelike Adventures and Dungeons 1.39 we are getting reports of Naga spawning in the overworld in normal vanilla biomes.

**Comment by ghost** [comment]
Unfortunately it's been well over a year since I fixed this, and don't remember the cause. I also no longer play Minecraft, and I don't have the files that contained the config change readily available as they're deep in some archives.
