### ISSUE TITLE
Mark conquered Landmarks on Twilight Forest Magic Map

### ISSUE THREAD

**Issue by FeaZt** [TeamTwilight/twilightforest#701]
What if all killed bosses will be marked on the map? Like with some X on them?

**Comment by Megalodab** [comment]
would love to have this. and to take it a step further, you could enable/disable automatic X's or some other icon appearing on map after u beat a boss. and u can select to add or remove X's to areas too. So like if you wanted to cross off a hollow hill after looting it, even tho theres no boss, you have the option to do so yourself. And make sure this carries over when you make a copy of the map.

Otherwise the current idea is to go over with banners and I think theres a way in one of the recent vanilla updates to put icons on the map based on where a banner is. but obviously this is would be super annoying to go back there

**Comment by Tamaized** [comment]
This isn't possible at the moment without reading world data which is very expensive and will drop tps

**Comment by Megalodab** [comment]
Maybe instead of trying to do it automatically if that's too expensive, there can just be a manual option to add a marker over certain monuments. So the player can just decide to add/remove a marker whenever they want. 
Never thought to ask this idea but it would help me so much lol my current way of keeping track of whats already explored is such a mess
