### ISSUE TITLE
Boss mob AI enhancement ideas.

### ISSUE THREAD

**Issue by SirAron111** [TeamTwilight/twilightforest#719]
Naga: prevent it from getting stuck on its own maze walls especially if mob grifing is disabled. Have it have independent hp so that the head is the main part but if you cut of a body part it doesn’t get shorter it just splits in 2 having the cut of body chase you.

Lich: Limit its TP to be inside his tower chamber so he doesn’t port into the stairways or walls (making the top of the tower a bit bigger for more arena space) and make it so that his shield only disappears after hitting his spells back at him or when getting rid of his minions first.

Hydra: Prevent players from getting under it where it can’t attack them by giving it a push back that knocks the player far away when they get to under it. Make it so that you need to kill a certain settable amount of heads to kill it instead of just killing the body which is to easy. Have the heads use different attacks so that one always spits fireballs/ one always uses melee/ one uses poison breathe etc.

Uhrghast: have it use special skills other than this nearly useless tear rain makes it summon lightning onto the player or something like that.

Snow Queen: again needs a way bigger arena so she isn’t too easy to corner. Make her use different attacks like a spin attack or shoot icicles at the player. And summon some snow minions.
As for the last boss don’t know if he ever comes: Make him something like a fallen Angle (not to big, Big Bosses always get stuck on things) thingy that can teleport around and use a mixture of debuffs at random shoot some kind of ranged thingy and attack melee when the player gets to close until he teleports again.

And lastly the damage they do should be settable in the config somewhere so modpack makers can use them and better adjust them without you breaking the standard balance of the mod (but with some modpacks its really hard to take these bosses serious even if they would fit well if just a bit stronger and the player couldn’t literally stand still when getting hit taking no dmg)

Well Thank you for reading this been a fan of the mod since its early times. I am currently using it in my modpack (Dimension Zero) but as players progress the bosses feel way to little like bosses as I can’t configure them much.

GZ
SirAron

**Comment by GizmoTheMoonPig** [comment]
Its always nice to see suggestions for boss improvements. I'll go through these before closing this, since certain things have either been implemented, planned, or are out of scope. 
Naga: having the naga split up would change the entire dynamic of the boss fight, which is something we're not looking to do. I dont think the Naga will be changed very much from what it currently is. The Naga being stuck in walls with griefing off is a valid concern and has been fixed since this was written. 
Lich: a bigger boss room will be coming in the rework, and this should fix the stair issue. As for the shields, we encourage players to get creative. If someone brings splash potions to get rid of his shields, thats awesome! They should be able to use those to knock out shields. I made it in newer versions that the Lich will now absorb his minions and heal if he gets below half health in his 2nd phase. This ensures the 3rd phase always happens and encourages players to actually kill the minions before going after the lich itself.
Hydra: the body was always supposed to push players and entities out of it, that just wasnt fixed until pretty recently. In regard to damaging the body, the idea is to damage the heads anyway, since the heads take more damage when hit anyway. We discourage hitting the body anyway with the bite attack, but it shouldnt be impossible to do so. 
Ur-Ghast: im not against the idea of adding some other minor attack to the ur-ghast fight, but "summoning lightning on the player" is not the way to do this. The ur-ghast doesnt have control of the weather, and stright up punishing the player for absolutely no reason is not a good way to make a fight. 
Snow Queen: a bigger arena will come with the rework. The Snow Queen has the saddest boss room out of any boss, and that desperately needs to change. Much like the rest of the Aurora Palace, the Snow Queen herself is kind of a buggy boss fight atm. She has 3 attacks, but they dont work too well in such a cramped space, not to mention she easily gets stuck under the floor after smashing downwards. We'll do more justice for the Snow Queen when we get to her, I promise. 

Boss health and damage can be configured through other mods, or even through vanilla thanks to attributes. We have no plans to add a way to change this in the mod itself, as youre encouraged to explore this dimension very early on. This premise will never change. 

Again, thank you for the suggestion, we love to see people's thoughts on things from the mod!
