### ISSUE TITLE
Twilight Forest: 1-2 fps only on a specific PC

### ISSUE THREAD

**Issue by kamild1996** [TeamTwilight/twilightforest#733]
Minecraft: 1.12.2
Forge version: 14.23.5.2811
Twilight Forest version: 3.8.689
Java: AdoptOpenJDK 1.8u212 x64
OS: Windows 10 x64
PC specs: Core i5-3350P, Radeon R9 280X, 16 GB RAM
Link to log: https://gist.github.com/kamild1996/d15f72cc20143461041df48b41c6b86f

Once Twilight Forest is installed, the game is constantly stuck at 1-2 fps. Once Twilight Forest is removed, the framerate goes back to normal. Tested with and without OptiFine, FoamFix or BetterFps, with different combinations.
There are a few other mods also running along Twilight Forest (see: https://gist.github.com/kamild1996/c94b77e3c1824044b76b8005dcc8e270), but **this same exact** set of mods with Twilight Forest runs perfectly fine on another computer, with same Windows version, Forge version, same Java distribution but better specs (i3-3570K, GTX 1070, SSD).

**Comment by bool3max** [comment]
I am able to reproduce exactly the same behaviour.

1.12.2, latest 64bit Java, 4GB allocated, latest recommended Forge build, no optimization mods, game runs perfect @100+ FPS with ~30 mods.

Once I add TF, the game drops to an unplayable 10 fps, in all dimensions. Remove TF, game runs fine again.

Changing visual settings (VSYNC, texture quality etc...) doesn't help, as doesn't adding/removing optimization mods (Optifine, FoamFix, BetterFPS).

**Comment by Andromander** [comment]
The fact the lag occurs *outside* of the Twilight Forest indicates that there is something else at play. I would also advise installing Phosphor to see whether this will resolve the issue (do not use Optifine, that may actually lower performance).

**Comment by bool3max** [comment]
I've just tested it with Phosphor 0.2.4 (and no other optimization mods) and unfortunately the behavior is still the same.

**Comment by thematbrown** [comment]
I have a friend that is having the exact same issue. Other mods and modpacks work fine but the moment that TF is added, it drops to about 1-2 FPS. Everyone else I had test this mod works fine and they are running on lower end laptops. One thing I noticed is that the one who is experiencing the lag is using Radeon integrated graphics. Could that possibly have something to do with it?

**Comment by bool3max** [comment]
@thematbrown I've solved the problem by dragging the "Mipmap Levels" slider to 0. It went from an extremely laggy 20 FPS to 190+ w/ no lag, w/o any optimization mods. 

I'm using an AMD GPU and my friend who also has an AMD GPU also experienced this problem. 

So, must be something AMD related.

**Comment by jellysquid3** [comment]
I suspect this issue is due to animated texture ticking. Minecraft, in its infinite wisdom, uploads texture data one-by-one for each animated texture, for every mipmap level, every frame. Even if a texture is not visible in the world, it will still be processed and uploaded to the graphics card. This gets worse with larger textures as all textures are stored on a single 2D image, meaning each row of pixels for a texture has to be uploaded individually.

For non-AMD cards, this whole process is not exactly fast and introduces a lot of performance penalties. However, on AMD cards, that mipmap generation step is significantly slower and is performed each and every time a single row of pixels is uploaded. This can absolutely destroy performance and produce the results many users are reporting here.

You have three solutions.
- Disable mipmapping at the expense of distant textures in the world looking [significantly worse](http://jolstatic.fr/www/captures/1478/5/46875.gif). This might be a perfectly suitable option for some people, but I can't stand it. It will bring the most significant performance improvement for all GPUs.
- Install VanillaFix (which I have mixed feelings about) or OptiFine (which I definitely do not recommend). These two mods change the animated texture system to only upload data for textures currently visible in the world and bring a significant improvement regardless of GPU, albeit not as much as outright disabling mipmaps. The mods may also break animated textures for some mods which use them in esoteric ways. 
- Install FoamFix. The mod implements a better texture uploading mechanism for AMD cards, but the bottleneck here is _still_ uploading textures. It does nothing to reduce the number of textures that are uploaded per frame. This is the safest option, but the improvement to performance is not as great as the other two options.

I've not checked whether or not the system for animated textures in Minecraft 1.13+ is just as bad as it is in Minecraft 1.12, but I've not heard any news to suggest it's changed.

**Comment by thematbrown** [comment]
@bool3max @jellysquid3 Thank you both for the suggestions! I found that setting the Minimap levels to OFF was able to boost FPS and made the game playable so thank you for that!

**Comment by ThatOneCubanDude** [comment]
I was having this same issue and also found that turning minimap off solved the problem. However, I think I found an even better, less disruptive, solution in terms of preserving graphic quality. If you have Optifine, you can navigate to the "Performance" settings and turn on "Smart Animations." This option says it only animates the textures currently on the screen when turned on. This completely solved the fps problem for me and I could turn minimap all the way up again. I also suggest getting Phosphor because it greatly increases the world generation time while using Twilight Forest and could smooth things out a bit if you still have some frame drops. I also use AMD so maybe it is an AMD specific problem.

**Here are the links and versions that I use for each mod:**
 - [Twilight Forest 3.10.1013](https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest) 
 - [OptiFine 1.12.2 HD U F4](https://optifine.net/downloads)
 - [Phosphor 0.2.6](https://www.curseforge.com/minecraft/mc-mods/phosphor)

**The rest of my specs:** 
- Minecraft: 1.12.2
- Forge version: 14.23.5.2847
- PC specs: AMD Ryzen 3 2200G, Radeon Vega Graphics(APU), 16 GB RAM

**Comment by Andromander** [comment]
Since this issue is specific to hardware as well as base game logic, there isn't much we can do on this side except not animating textures, and that's not a good idea. Some solutions have been provided above for people experiencing lag due to animated textures.
