### ISSUE TITLE
Null Item Stack

### ISSUE THREAD

**Issue by NielsPilgaard** [TeamTwilight/twilightforest#758]
Forge version: 1.12.2-14.23.5.2836
Twilight Forest version: twilightforest-1.12.2-3.8.689-universal
Link to crash log: https://pastebin.com/KWmDbJWR

Steps to reproduce:
1. Make an instance with Draconic Evolution and Twilight Forest (and dependencies)
2. Get a Draconic Axe
3. Right click a Large Twilight Oak
4. Crash

What I expected to happen:
The tree to be harvested

What happened instead:
Crash

I reported the issue to Draconic Evolution first here: https://github.com/brandon3055/Draconic-Evolution/issues/1333

**Comment by bs2609** [comment]
To clarify, did you reproduce this crash with *only* Draconic Evolution and Twilight Forest (and dependencies)? If so, can you post the crash report from that instance, otherwise, can you try to reproduce it with only those mods.

The crash report you linked here has a much larger modlist, which makes it much harder to track down any issue.

**Comment by NielsPilgaard** [comment]
I did not no, I'll try to reproduce it now.

**Comment by NielsPilgaard** [comment]
I cannot reproduce it with only DE, TW and dependencies, my apologies for the report :)
