### ISSUE TITLE
Crash with Enderman Evolution

### ISSUE THREAD

**Issue by Cazadorsniper** [TeamTwilight/twilightforest#768]
Forge version: 14.23.5.2838
Twilight Forest version: 1.12.2-3.8.689-universal
Link to crash log: 
https://pastebin.com/5ihxEb2s
https://pastebin.com/xXzJEPpG (with mob grinding utils)

Steps to reproduce:
1. Have any Enderman from Enderman Evolution get damaged.

What I expected to happen:
For the enderman to be killed like normal.

What happened instead:
Crash

**Comment by bs2609** [comment]
Crash is fixed by 3ab2ef5aca4e0739a6d12b57ccadbfa05c25d909, although it is worth noting that support for the capability in question is built-in by Forge which makes its absence here a little questionable, as the [entity involved](https://github.com/p455w0rd/EndermanEvolution/blob/master/src/main/java/p455w0rd/endermanevo/entity/EntityEvolvedEnderman.java) doesn't have any custom capability handling code.
