### ISSUE TITLE
Attempting to fire a cicada from an Immersive Engineering railgun crashes all clients near the railgun user

### ISSUE THREAD

**Issue by Questwizard** [TeamTwilight/twilightforest#775]
Forge version: 1.12.2-14.23.5.2838
Twilight Forest version: 1.12.2-3.8.689
Link to crash log:  https://gist.github.com/Questwizard/bd68d019572d6b5cd3838a60a058d56e

Steps to reproduce:
1. Put cicadas in your inventory.
2. Charge and fire an Immersive Engineering railgun. 

What I expected to happen: Cicada should have fired from the railgun.

What happened instead: Both clients connected to the server and in the area of the railgun user crashed.

**Comment by bs2609** [comment]
Can you post your `latest.log` file as well?

**Comment by Questwizard** [comment]
[2019-07-13-5.log.gz](https://github.com/TeamTwilight/twilightforest/files/3389653/2019-07-13-5.log.gz)
This was my log. The other player on the server is the one who fired the railgun.

**Comment by bs2609** [comment]
Log from the server would also be helpful.

In addition:
* Does this happen consistently?
* Does this happen only with Cicadas, or can other railgun projectiles cause this?

From the crash report you posted, the crash occurs in Immersive Engineering's code, but it is most likely caused by some other mod using the entity data manager wrong. This can cause client-server ID mismatches, which leads to these sort of crashes.

**Comment by Questwizard** [comment]
It did happen twice in a row with the same error. We never tried anything other than standard railgun shots and cicadas. We ended up removing Immersive Engineering altogether not long after because it was also causing serious rendering issues in other mods, so I wouldn't be able to test with much else.

**Comment by eman1can** [comment]
I had the same problem in my world. Didn't try to fire cicadas, but firing the IE Railgun at all would cause my client to crash.

**Comment by GizmoTheMoonPig** [comment]
Havent been able to replicate this in 1.16, so im gonna assume this isnt an issue.
