### ISSUE TITLE
Suggestions about Iron Ladders

### ISSUE THREAD

**Issue by FlyingCart000** [TeamTwilight/twilightforest#828]
One classic feature of the Twilight Forest mod is that as a new dimension mod, it has no impact in the other worlds unless you open the Twilight Forest portal and enter the Twilight Forest. This feature makes the Twilight Forest separated from the overworld and also becomes easier for Servers to take control.

But the addition of the new item, Iron Ladders, breaks this rule. By using iron nuggets and iron bars, you can create it without anything from the Twilight Forest, and such items belongs to mods such as furniture mod, not new dimension mods especially Twilight Forest.

In order to keep this feature, I personally suggest that it might be better to change the crafting recipe by adding/replacing with the Twilight Forest only items such as ironwood ingots/nuggets (which might be obtained by Smelting ironwood items?) and make it unable to craft before entering the Twilight forest.

Also, it can be a good idea to add a series of new ironwood version of blocks made of iron.

<img width="250" alt="Screen Shot 2019-10-19 at 3 31 11 PM" src="https://user-images.githubusercontent.com/56772301/67150529-80aef580-f286-11e9-938a-0577c7d17938.png">

**Comment by GizmoTheMoonPig** [comment]
we've introduced a few blocks that also break this rule since then. Hollow logs, banisters, skull candles, twisted stone, and even spiral bricks dont require any TF materials to make them. I dont know if having every recipe be TF resource exclusive was ever something we needed to follow, but since I dont see us reverting any of these things just to follow this unspoken "rule" im gonna close this. Appreciate your suggestion!
