### ISSUE TITLE
[Suggestion] A way to temporarily and completely stop worldgen in the Twilight Forest

### ISSUE THREAD

**Issue by yezhiyi9670** [TeamTwilight/twilightforest#874]
I suppose that A LOT of players have experienced this: The player was fighting with a strong boss. Suddenly, a lag spike occured and lasted for 2 seconds. Then, the player died "for no reason".

I heard that the world generation of the Twilight Forest is extremely inefficient (maybe it is true). I guess this is the biggest reason of lag spikes.

I know this is difficult to change because of a lot of foilage in the forest which makes decorating and lighting very slow. World generation seem to be necessary for exploration, but it has no use when the player is fighting in a small, enclosed area, so a keybind/command to completely stop worldgen during a fight can be a good idea.

Note: The game should push players back when they're attempting to go out of the bounds of generated chunks.

EDIT: If it's not good or not possible to do so on dedicated servers, then it can be singleplayer-only, as most server owners have a way to deal with the lag.

**Comment by Andromander** [comment]
That's...not only a logistical nightmare, but a bad solution to a temporary problem. It's impossible to "stop" generation in a game with procedural world generation, as it will break how features generate.

Your best options are to pre-generate chunks (this can be done with the /forge command), set a world border, and install mods that improve performance, such as Phosphor (it improves generation significantly), BetterFPS (improves frame rate via various options), or FoamFix (reduces Minecraft's use of RAM). Consider reducing on graphics, such as Fog distance.
The only "inefficiency" is Minecraft's way of handling lighting and world generation.

It may also be unnecessary to add, since current focus is on porting to 1.15.2, where generation and lighting will be handled much differently and potentially better.

**Comment by yezhiyi9670** [comment]
Thanks (the pregeneration worked fine).

**Comment by Tamaized** [comment]
I just want to note since it was mentioned...

"I heard that the world generation of the Twilight Forest is extremely inefficient (maybe it is true). I guess this is the biggest reason of lag spikes."

This is completely false. We've done all we could for world gen. The bottle neck lands on how vanilla itself calculates skylight during world generation. The Phosphor mod takes it upon itself to be invasive with vanilla in order to solve this for everybody.
