### ISSUE TITLE
{ SUGGESTION } Block and Chain modifications?

### ISSUE THREAD

**Issue by TotallyRealReimu** [TeamTwilight/twilightforest#892]
The Block and Chain feels really weird. I think it should have more reach because it's a flail. It adds more depth to the combat, as you can space out your fights more while the cooldown means less DPS and a little more strategy, adding a bit of spice to the fights you take part in.

**Comment by Drullkus** [comment]
It's not a flail. How does it feel weird?

You're already getting a crazy range of 16 blocks with this item, so I don't think we should be adding more range. There isn't any artificial cool-down. You get to throw the block again as soon as it comes back to you, which is fair.

You get to brutally wipe out crowds with the block and chain because the ball keeps going even after hitting 4 mobs in a group with a chance of hurting them *again* as it comes back to you. In fact it's so damaging that usually it takes 2 throws to kill skeletons and zombies, but at the cost of you being vulnerable and thus requiring you to invest into tankier armor, since the Block and Chain is considered a tank-type weapon. Not to forget that it actually breaks kinda fast too compared to like a diamond sword.

Not only this, it's also prohibitively expensive, as you have to collect 81 knightmetal shards to craft this thing.
