### ISSUE TITLE
(1.16) Block and Chain cannot harvest some blocks that require a pickaxe

### ISSUE THREAD

**Issue by Inonedn** [TeamTwilight/twilightforest#912]
Intended Result: Harvest block properly
Result: Block is destroyed, leaving nothing behind

**Comment by GizmoTheMoonPig** [comment]
tested this in 1.17, every block it was able to break dropped. Im not sure if this was an actual issue at one point or if it was a mod conflict of some kind, but it seems to be working fine now. If you run into this on later versions please reopen this and send me your modlist, otherwise I will consider this solved
