### ISSUE TITLE
Minecraft Hamachi server 

### ISSUE THREAD

**Issue by T1m0123** [TeamTwilight/twilightforest#980]
Forge version: 1.12.2-14.23.5.2854
Twilight Forest version: (1.12.2-3.9.974-universal)

Steps to reproduce:
1. I downloaded the TF mod and forge
2. Put it in the mods folder in AppData/.minecraft/mods, and in the server file

What I expected to happen:
I expected that it works both in single player and on my server.

What happened instead:
It worked in single player, but on my server I could see every single item of the mod in creative, but when I took the item and placed it on the ground it appeared for half of a second and instantly disappeared.

PS. the minimap mod worked fine

**Comment by Andromander** [comment]
Any of the following could have occurred:
1. The server is running on vanilla rather than Forge. If the `/forge` command shows up as an invalid command, the server is vanilla.
2. Twilight Forest is not installed on the server. If the `/forge` command did run but you are unable to place blocks, then that means the mod isn't on the server, only on your client.

**Comment by Tamaized** [comment]
This means you haven't installed it correctly on your server. Basic troubleshooting is needed on your end.
1.) Does the `/forge` command work? If not then you're running a vanilla server.
2.) Does the `/tffeature` command work? If not then you haven't placed the mod jar in the correct location. `{server root}/mods/`

Going to close this as it's a generic issue not a Twilight Forest specific issue.
